### ISSUE TITLE
Android Basics: Fragments Navigation component

### ISSUE THREAD

**Issue by DemonazGH** [google-developer-training/android-basics-kotlin-words-app#100]
**URL of codelab**

https://developer.android.com/codelabs/basic-android-kotlin-training-fragments-navigation-component?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-3-pathway-2%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-fragments-navigation-component#3

**In which task and step of the codelab can this issue be found?**
step 4

**Describe the problem**
It is lapse. Marked it in the screenshot

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._
![image](https://user-images.githubusercontent.com/51007840/116444313-46e88300-a85d-11eb-9db9-1b7ce36314b3.png)

**Comment by jtavva** [comment]
@DemonazGH 
Thank you for reaching out to us.
This should be fixed now.
