### ISSUE TITLE
Android Basics: Fragments Navigation component

### ISSUE THREAD

**Issue by mgssk** [google-developer-training/android-basics-kotlin-words-app#101]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-fragments-navigation-component?authuser=1&continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-3-pathway-2%3Fauthuser%3D1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-fragments-navigation-component

**In which task and step of the codelab can this issue be found?**

**Describe the problem**
The code at the bottom of the "Use FragmentContainerView in MainActivity" section is wrong.
as is:
<xmlns:android="http://schemas.android.com/apk/res/android"
to be:
<FrameLayout xmlns:android="http://schemas.android.com/apk/res/android"

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by jtavva** [comment]
@mgssk 
Thank you for reaching out to us.
This should be fixed now.
