### ISSUE TITLE
Android Basics: Fragments Navigation component

### ISSUE THREAD

**Issue by Firreit** [google-developer-training/android-basics-kotlin-words-app#102]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-fragments-navigation-component?authuser=1&continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-3-pathway-2%3Fauthuser%3D1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-fragments-navigation-component#0

**In which task and step of the codelab can this issue be found?**
1 "Before you begin"

**Describe the problem**
Typo - "fragmen" instead of "fragment" here:
In the example below, both the navigation UI on the left and the content on the right can each be contained in a separate fragmen.

**Steps to reproduce?**
1. Go to the codelab
2. See error in the article just above the second screenshot

**Additional information**
![image](https://user-images.githubusercontent.com/38285557/116803555-631c4680-ab21-11eb-8737-c0a1cbb400f0.png)

**Comment by jtavva** [comment]
@Firreit 
Thank you so much for reporting this issue. This is fixed and will be published soon.
