### ISSUE TITLE
Android Basics: Fragments Navigation component

### ISSUE THREAD

**Issue by Firreit** [google-developer-training/android-basics-kotlin-words-app#103]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-fragments-navigation-component?authuser=1&continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-3-pathway-2%3Fauthuser%3D1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-fragments-navigation-component#3

**In which task and step of the codelab can this issue be found?**
4 "Create Fragments and layout Files"

**Describe the problem**
Text says "Update tools:context in fragment_letter_list.xml to .LetterListFragment", but in the code below it is ".WordListFragment"

**Steps to reproduce?**
1. Go to the codelab
2. Scroll to the bottom
3. See the error

**Additional information**
Screenshot:
![image](https://user-images.githubusercontent.com/38285557/116804482-cc9f5380-ab27-11eb-9b2c-f98c001ee751.png)

**Comment by jtavva** [comment]
@Firreit 
Thank you for reaching out to us.
This should be fixed now.
