### ISSUE TITLE
Android Basics: Fragments Navigation component

### ISSUE THREAD

**Issue by GregSaintJean** [google-developer-training/android-basics-kotlin-words-app#104]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-fragments-navigation-component?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-3-pathway-2%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-fragments-navigation-component#7

**In which task and step of the codelab can this issue be found?**
8. Using the Navigation Graph/Step 5

**Describe the problem**
The tag for FrameLayout is incorrect. It's labeled "xmlns:android="http://schemas.android.com/apk/res/android" But it should be labeled "Framelayout"

**Steps to reproduce?**
Do you really need this? Just go here -> "https://developer.android.com/courses/pathways/android-basics-kotlin-unit-3-pathway-2#codelab-https://developer.android.com/codelabs/basic-android-kotlin-training-fragments-navigation-component" and go to "Fragments and Navigation Component"

**Versions**
Not needed

**Additional information**
![mistake](https://user-images.githubusercontent.com/9660745/117471450-dc52d980-af25-11eb-9875-3c117a193c98.png)

**Comment by jtavva** [comment]
@GregSaintJean 
Thank you for reaching out to us.
This should be fixed now.
