### ISSUE TITLE
Android Basics: Activities and intents

### ISSUE THREAD

**Issue by robertCSN** [google-developer-training/android-basics-kotlin-words-app#105]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-activities-intents?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-3-pathway-1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-activities-intents#6

**In which task and step of the codelab can this issue be found?**
Step 7 Set up Implicit Intent

**Describe the problem**
companion object {
   val LETTER = "letter"
   val SEARCH_PREFIX = "https://www.google.com/search?q="
}

I think 'const' should be added, as mentioned in step 6.
   const val LETTER = "letter"
   const val SEARCH_PREFIX = "https://www.google.com/search?q="

Thanks.

**Comment by calren** [comment]
Yes, that's indeed correct! This is now fixed in the codelab
