### ISSUE TITLE
Android Basics: Fragments Navigation component

### ISSUE THREAD

**Issue by david20571015** [google-developer-training/android-basics-kotlin-words-app#106]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-fragments-navigation-component?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-3-pathway-2%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-fragments-navigation-component#3

**In which task and step of the codelab can this issue be found?**
4. Create Fragment and layout Files / step 3

**Describe the problem**
The 3rd step says "Update tools:context in fragment_letter_list.xml to .LetterListFragment", but the code below shows ".WordListFragment". It should be ".LetterListFragment".

**Steps to reproduce?**
1. Go to the codelab.
2. Click on 4. Create Fragment and layout Files and scroll down to step 3.
3. See the error.

**Additional information**
![螢幕擷取畫面 2021-05-10 042905](https://user-images.githubusercontent.com/51911434/117586027-464ac900-b148-11eb-9610-f50b3f986595.png)

**Comment by jtavva** [comment]
Thank you so much for reporting this issue. This is fixed and will be published soon.
