### ISSUE TITLE
Android Basics: Activities and intents

### ISSUE THREAD

**Issue by Jherscu** [google-developer-training/android-basics-kotlin-words-app#107]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-activities-intents?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-3-pathway-1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-activities-intents#6

**In which task and step of the codelab can this issue be found?**
Words App
Step 7: Set Up Implicit Intent
#1

**Describe the problem**
In the previous step we are told to create the companion object with - const val LETTER = "letter".

In this next step the same code sample omits the const, leading to confusion as to the necessity of the const in the first place.

Should the second variable, SEARCH_PREFIX, include the const as well, or not?

**Steps to reproduce?**
1. Go to... N/A
2. Click on... N/A
3. See error... N/A

**Versions**
_Android Studio version:_  N/A
_API version of the emulator:_  N/A

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._
![Screen Shot 2021-05-09 at 8 30 04 PM](https://user-images.githubusercontent.com/62267982/117592160-9d7b7a00-b105-11eb-9b8a-e8d774b2b675.png) --step 6

![Screen Shot 2021-05-09 at 8 31 06 PM](https://user-images.githubusercontent.com/62267982/117592169-a9ffd280-b105-11eb-877a-1eab64613f18.png) --step 7

**Comment by calren** [comment]
That's a good point! Another similar issue was filed (https://github.com/google-developer-training/android-basics-kotlin-words-app/issues/146), so we'll be closing this one in favor of the other one.
