### ISSUE TITLE
Android Basics: Collections

### ISSUE THREAD

**Issue by githubspl** [google-developer-training/android-basics-kotlin-words-app#108]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-collections?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-3-pathway-1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-collections#4

**In which task and step of the codelab can this issue be found?**

"5. Make word lists"

**Describe the problem**

In the following step, there is no need to sort a list that contains only one string.  Please remove the call to the sorted() function.

--- Excerpt begins ---
10. Try changing the code to create a list of one random word that starts with the letter c. What do you have to change in the code above?

val filteredWords = words.filter { it.startsWith("c", ignoreCase = true) }
    .shuffled()
    .take(1)
    .sorted()
--- Excerpt ends ---

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by calren** [comment]
That's a good point, and we've taken out the extra `sorted()` step. Thanks for filing!
