### ISSUE TITLE
Android Basics: Fragments Navigation component

### ISSUE THREAD

**Issue by dfehlauer** [google-developer-training/android-basics-kotlin-words-app#109]
https://developer.android.com/codelabs/basic-android-kotlin-training-fragments-navigation-component?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-3-pathway-2%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-fragments-navigation-component#5

Step 6

error message for 
override fun onCreateView()---the override is underlined in red and tells me onCreateView overrides nothing.
same thing for onViewCreated and onDestroyView

![image](https://user-images.githubusercontent.com/84147765/118162648-ff323180-b3ee-11eb-9bf9-3ad0647b8399.png)

**Comment by jtavva** [comment]
@dfehlauer 
Thank you for reaching out to us.
To further debug this issue, please give use the entire `WordListFragment.kt` file.
