### ISSUE TITLE
Android Basics: Collections

### ISSUE THREAD

**Issue by ps-noob** [google-developer-training/android-basics-kotlin-words-app#110]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-collections?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-3-pathway-1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-collections#3

**In which task and step of the codelab can this issue be found?**
Collections in Kotlin codelab 4th step
![missing image](https://user-images.githubusercontent.com/70065210/118232313-f94f5580-b4ad-11eb-8958-df7796cff001.png)
![missing image](https://user-images.githubusercontent.com/70065210/118232326-ffddcd00-b4ad-11eb-868f-81fb26ea249c.png)

**Describe the problem**
In the fourth topic "Learn about lambdas and higher-order functions"  image is missing making it difficult to understand the topic

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._
![missing image](https://user-images.githubusercontent.com/70065210/118232429-28fe5d80-b4ae-11eb-9bc7-c9be7d725212.png)

**Comment by calren** [comment]
This was a temporary issue and should now be fixed. Thanks for filing!
