### ISSUE TITLE
Android Basics: Collections

### ISSUE THREAD

**Issue by Vadinhao** [google-developer-training/android-basics-kotlin-words-app#111]
**URL of codelab**

https://developer.android.com/codelabs/basic-android-kotlin-training-collections?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-3-pathway-1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-collections#3

**In which task and step of the codelab can this issue be found?**

![error_png](https://user-images.githubusercontent.com/69089418/118321708-a655bc80-b506-11eb-8dbc-4b03e70861ee.png)

**Describe the problem**

U don't have image on this page, fix it

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by jtavva** [comment]
@Vadinhao 
This should have been fixed.

**Comment by Vadinhao** [comment]
Thanks, good luck

Чт, 24 июня 2021 г. в 23:46, jtavva ***@***.***>:
