### ISSUE TITLE
Android Basics: Activities and intents

### ISSUE THREAD

**Issue by akhilendrajha** [google-developer-training/android-basics-kotlin-words-app#114]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-activities-intents?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-3-pathway-1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-activities-intents#7

**In which task and step of the codelab can this issue be found?**
Step 8 Setup Menu and icons

**Describe the problem**
The first step is to import two icons to represent the grid and list views. But there is no link provided to those icons.

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by jtavva** [comment]
@akhilendrajha 
Thank you for reaching out to us. 
Importing Material vector assets is explained in details in the previous units. It is important that you complete each unit in sequence.

As mentioned in the codelab: 

> First, you need to import two icons to represent the grid and list views. Add the clip art vector assets called “view module" (name it ic_grid_layout) and “view list" (name it ic_linear_layout). If you need a refresher on adding material icons, take a look at the instructions on [this](https://developer.android.com/codelabs/basic-android-kotlin-training-polished-user-experience?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-2-pathway-1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-polished-user-experience#3) page.

Please refer this codelab for refresher: https://developer.android.com/codelabs/basic-android-kotlin-training-polished-user-experience?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-2-pathway-1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-polished-user-experience#3

And import “view module" (name it ic_grid_layout) and “view list" (name it ic_linear_layout) vector assets.
