### ISSUE TITLE
Android Basics: Activities and intents: Inconsistent val declaration

### ISSUE THREAD

**Issue by johnlinp** [google-developer-training/android-basics-kotlin-words-app#117]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-activities-intents

**In which task and step of the codelab can this issue be found?**
7. Set Up Implicit Intent

**Describe the problem**
The code block:
```kotlin
companion object {
   val LETTER = "letter"
   val SEARCH_PREFIX = "https://www.google.com/search?q="
}
```
However, in the previous step "6. Set Up DetailActivity", the value `LETTER` was declared as:
```kotlin
const val LETTER = "letter"
```
The difference is the `const` keyword. It might cause confusion for readers to see.

**Comment by jtavva** [comment]
@johnlinp 
Thank you so much for reporting this issue. This is fixed and will be published soon.
