### ISSUE TITLE
Android Basics: Fragments Navigation component: Lack of explanation of what a "up button" is

### ISSUE THREAD

**Issue by johnlinp** [google-developer-training/android-basics-kotlin-words-app#118]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-fragments-navigation-component

**In which task and step of the codelab can this issue be found?**
8. Using the Navigation Graph

**Describe the problem**
The final step of this page tell us to implement the `onSupportNavigateUp()` method. The description says it allows us to handle the "up button", but didn't tell us what an "up button" is. What's worse, it didn't explain what `super.onSupportNavigateUp()` or `navController.navigateUp()` is actually doing. Therefore, it's really unclear what this step try to achieve.

**Comment by vishnukaushik** [comment]
The up button is generally meant as *back* button.

**Comment by vishnukaushik** [comment]
> **URL of codelab**
> https://developer.android.com/codelabs/basic-android-kotlin-training-fragments-navigation-component
> 
> **In which task and step of the codelab can this issue be found?**
> 8. Using the Navigation Graph
> 
> **Describe the problem**
> The final step of this page tell us to implement the `onSupportNavigateUp()` method. The description says it allows us to handle the "up button", but didn't tell us what an "up button" is. What's worse, it didn't explain what `super.onSupportNavigateUp()` or `navController.navigateUp()` is actually doing. Therefore, it's really unclear what this step try to achieve.



> **URL of codelab**
> https://developer.android.com/codelabs/basic-android-kotlin-training-fragments-navigation-component
> 
> **In which task and step of the codelab can this issue be found?**
> 8. Using the Navigation Graph
> 
> **Describe the problem**
> The final step of this page tell us to implement the `onSupportNavigateUp()` method. The description says it allows us to handle the "up button", but didn't tell us what an "up button" is. What's worse, it didn't explain what `super.onSupportNavigateUp()` or `navController.navigateUp()` is actually doing. Therefore, it's really unclear what this step try to achieve.

The up button is the *back* button that's generally present in appbar

**Comment by johnlinp** [comment]
Thanks @vishnukaushik for the explanation. However, my real point is that it should have been clearer in the tutorial.

For example, in the next tutorial https://developer.android.com/codelabs/basic-android-kotlin-training-shared-viewmodel, there is a sentence says:

> Change the title in the app bar (also known as action bar) for each fragment using the NavController and display an Up (←) button.

It's better because at least it shows that the up button looks like "←".

**Comment by osuleymanova** [comment]
@johnlinp 
Thank you for contacting us and leaving your feedback.
