### ISSUE TITLE
Android Basics: Activities and intents - Missing onClickListener

### ISSUE THREAD

**Issue by adalius** [google-developer-training/android-basics-kotlin-words-app#12]
https://developer.android.com/codelabs/basic-android-kotlin-training-activities-intents?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-3-pathway-1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-activities-intents#6

Step 1: "Open up WordAdapter and in the button's onClickListener in onBindViewHolder. Start by creating a URI for the search query."

Problem: There is no onClickListener in the onBindViewHolder, or in WordAdapter.kt in the provided code at all. There is one in the LetterAdapter, so it's unclear if WordAdapter is a typo and the LetterAdapter should be changed, or if WordAdapter needs one added.

**Comment by jtavva** [comment]
@adalius 
Thank you so much for reporting this issue. This is fixed and will be published soon.
