### ISSUE TITLE
Android Basics: Fragments Navigation component

### ISSUE THREAD

**Issue by Java-driod** [google-developer-training/android-basics-kotlin-words-app#124]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-fragments-navigation-component?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-3-pathway-2%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-fragments-navigation-component#3

**In which task and step of the codelab can this issue be found?**
Fragments and the Navigation Component codelab, task 4 ("Create Fragment and Layout Files"), step 3

**Describe the problem**
Let me preface this by saying I'm very new to programming, and really don't know what I'm talking about. But, I think one of the example codes may be wrong. In the Fragments and the Navigation Component codelab, on step 4, at the 3rd part of it, the directions say to "Update tools:context in fragment_letter_list.xml to .LetterListFragment " but, the little example box doesn't do this. The example for fragment_letter_list.xml has "tools:context=".WordListFragment" " I might be wrong here, but I think there was just a mistake in the writing. If you are one of the writers or play I role in creating these codelabs, I want to thank you. They have been very helpful for me to learn Kotlin! Have a great rest of your day! :)

**Steps to reproduce?**
1. Go to...Fragments and the Navigation codelab
2. Click on...Step 4: Create Fragment and Layout Files
3. See error...On the "3." part of it. The directions and the example code box do not match.
![Screen Shot 2021-05-23 at 11 38 55 AM](https://user-images.githubusercontent.com/78508065/119267183-79b33c00-bbbb-11eb-8ef0-3ae942b35320.png)

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by jtavva** [comment]
@Java-driod 
Thank you so much for reporting this issue. This is fixed and will be published soon.
