### ISSUE TITLE
Android Basics: Creating Menu in Activities and intents - add detailed instructions

### ISSUE THREAD

**Issue by adalius** [google-developer-training/android-basics-kotlin-words-app#13]
https://developer.android.com/codelabs/basic-android-kotlin-training-activities-intents?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-3-pathway-1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-activities-intents#7

Task 8, one of the last un-numbered steps.

It tells you to go to res>menu, but that folder doesn't exist. At this point in all the code bases up to this point, adding a new resource folder I don't believe has been discussed. Nor does it mention if it is mandatory/suggested/optional when using the New Resource Directory menu to set the Resource type to 'menu' for this new menu folder. It can be figured out with some thought but it deviates from the entire learning structure's 'hand-holding' for the first time a new action is performed to completely leave this step out.

**Comment by jtavva** [comment]
@adalius 
Thank you so much for reporting this issue. This is fixed and will be published soon.
