### ISSUE TITLE
Basic lessons should be basic!

### ISSUE THREAD

**Issue by KeefeOverby** [google-developer-training/android-basics-kotlin-words-app#130]
Can you make this "basic" lesson into a lesson that is not overly complicated, like with just one button that takes you to a second screen? 
Please!
I started an app that I feel would be more appropriate for a basic lesson.
https://github.com/KeefeOverby/Button-to-Second-Screen

**Comment by KeefeOverby** [comment]
Its almost impossible for a beginner to understand how to create one button, with this codelab, because we have to try to decipher the 13 buttons that you have in this codelab. Its way too complicated for a beginner/basic lesson!

**Comment by citrusella** [comment]
I found it pretty easy to understand (well, okay, it was appropriately scaffolded as to not be TOO easy but also not something I couldn't do without more help), but to be fair I finished the lessons that come before it in the Kotlin fundamental course before getting to it.

**Comment by KeefeOverby** [comment]
I was able to figure it out on my own without the complexity. See my example below, also this is my first experience with any code.
https://github.com/KeefeOverby/Button-to-Second-Screen
