### ISSUE TITLE
Android Basics: Fragments Navigation component

### ISSUE THREAD

**Issue by martinprice20** [google-developer-training/android-basics-kotlin-words-app#132]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-fragments-navigation-component

**In which task and step of the codelab can this issue be found?**
2. Starter Code

**Describe the problem**
Link provided in the text links to solution code, not starter code.

**Steps to reproduce?**
1. Go to...https://developer.android.com/codelabs/basic-android-kotlin-training-fragments-navigation-component?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-3-pathway-2%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-fragments-navigation-component#1
2. Click on...https://github.com/google-developer-training/android-basics-kotlin-words-app/tree/activities
3. See error... links to a repo with solution code, not starter code

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by jtavva** [comment]
The URL is correct, the starter code for this codelab is in the branch **activities**.
As mentioned in the codelab, the starer code is here -->  https://github.com/google-developer-training/android-basics-kotlin-words-app/tree/activities

Link to the solution is in the main branch -->  https://github.com/google-developer-training/android-basics-kotlin-words-app/tree/main
