### ISSUE TITLE
Android Basics: Fragments Navigation component

### ISSUE THREAD

**Issue by bernardsmith0892** [google-developer-training/android-basics-kotlin-words-app#134]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-fragments-navigation-component#7

**In which task and step of the codelab can this issue be found?**
Set Up the Navigation Graph

**Describe the problem**
Typo in this paragraph:

> Upon creating the XML file, you're presented with a new visual editor. Because you've already referenced `nav_graph` in the `FragmentContainerView`'s `navGraph` property, To add a new destination, click the new button in the top left of the screen and create a destination for each fragment (one for `fragment_letter_list` and one for `fragment_word_list`).

The specific portion is the second sentence: 

> Because you've already referenced `nav_graph` in the `FragmentContainerView`'s `navGraph` property, To add a new destination

**Comment by jtavva** [comment]
@bernardsmith0892 
Thank you for reaching out to us.
Could you please me be more specific describing the issue? Content in both the paragraphs seems to be same.

**Comment by bernardsmith0892** [comment]
@jtavva 
Thanks for the reply. It looks like the second sentence is missing a second clause. It ends with a comma and immediately goes into a new sentence.

**Comment by jtavva** [comment]
@bernardsmith0892 
Thank you so much for reporting this issue. This is fixed and will be published soon.
