### ISSUE TITLE
Android Basics: Collections

### ISSUE THREAD

**Issue by jahidulhub** [google-developer-training/android-basics-kotlin-words-app#135]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-collections?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-3-pathway-1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-collections#3

**In which task and step of the codelab can this issue be found?**
Higher-order functions
fun main() {
    val peopleNames = listOf("Fred", "Ann", "Barbara", "Joe")
    println(peopleNames.sorted())
    println(peopleNames.sortedWith { str1: String, str2: String -> str1.length - str2.length })
}

**Describe the problem**
Error:(4, 25) Kotlin: Type inference failed: fun <T> Iterable<T>.sortedWith(comparator: kotlin.Comparator<in T> /* = java.util.Comparator<in T> */): List<T>
cannot be applied to
receiver: List<String>  arguments: ((String, String) -> Int)

Error:(4, 36) Kotlin: Type mismatch: inferred type is (String, String) -> Int but kotlin.Comparator<in String> /* = java.util.Comparator<in String> */ was expected

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._
![Screenshot (15)](https://user-images.githubusercontent.com/49282533/120125464-7fc4a080-c1eb-11eb-9cda-72ed6c069f87.png)

**Comment by jtavva** [comment]
@jahidulhub 
Thank you for reaching out to us.
As mentioned in the codelab please use Kotlin Playground: https://developer.android.com/training/kotlinplayground

Check the following image for reference:

![image](https://user-images.githubusercontent.com/24260141/120377234-b70d7d00-c2d1-11eb-88a1-11bde3a9d811.png)
