### ISSUE TITLE
Android Basics: Fragments Navigation component

### ISSUE THREAD

**Issue by Joktaa** [google-developer-training/android-basics-kotlin-words-app#136]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-fragments-navigation-component?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-3-pathway-2%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-fragments-navigation-component#0

**In which task and step of the codelab can this issue be found?**
1) Before you begin

**Describe the problem**
"fragmen" must be "fragment"

**Comment by jtavva** [comment]
@Joktaa 
Thank you so much for reporting this issue. This is fixed and will be published soon.
