### ISSUE TITLE
Android Basics: Activities and intents

### ISSUE THREAD

**Issue by d8vd** [google-developer-training/android-basics-kotlin-words-app#138]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-activities-intents?authuser=3&continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-3-pathway-1%3Fauthuser%3D3%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-activities-intents#1

**In which task and step of the codelab can this issue be found?**
When you try to run the imported starter code.

**Describe the problem**
Failed to install the following Android SDK packages as some licences (sic) have not been accepted.
   build-tools;30.0.2 Android SDK Build-Tools 30.0.2
To build this project, accept the SDK license agreements and install the missing components using the Android Studio SDK Manager.
Alternatively, to transfer the license agreements from one workstation to another, see http://d.android.com/r/studio-ui/export-licenses.html

Requirement: 
Open Android Studio Menu > Preferences... > Appearance & Behavior > System Settings > Android SDK

Then select the "SDK Tools" tab and check the "Google Play Licensing Library" and click OK to install it.

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

Android Studio 4.2.1
Build #AI-202.7660.26.42.7351085, built on May 10, 2021
Runtime version: 11.0.8+10-b944.6916264 x86_64
VM: OpenJDK 64-Bit Server VM by N/A
macOS 10.16
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 8
Registry: external.system.auto.import.disabled=true
Non-Bundled Plugins: org.jetbrains.kotlin

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by jtavva** [comment]
@d8vd 
Were you able to resolve the issue on your own.

**Comment by d8vd** [comment]
Yes, by doing the following:

Open Android Studio Menu > Preferences... > Appearance & Behavior > System Settings > Android SDK
Then select the "SDK Tools" tab and check the "Google Play Licensing Library" and click OK to install it.

**Comment by jtavva** [comment]
@d8vd 
Thank you so much for replying to the query.
I will pass on your issue resolution to the development team thank you.
