### ISSUE TITLE
Android Basics: Fragments Navigation component

### ISSUE THREAD

**Issue by adalius** [google-developer-training/android-basics-kotlin-words-app#14]
https://developer.android.com/codelabs/basic-android-kotlin-training-fragments-navigation-component?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-3-pathway-2%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-fragments-navigation-component#7

Using Navigation Graph - Steps 1 & 5

In step 1, the wording "Replace the content of the FrameLayout" is a bit ambiguously worded as to whether you should replace the entire FrameLayout, the attributes inside the FrameLayout tag, or everything between the FrameLayout opening and closing tags. It would read better to say to replace the RecyclerView with the new FragmentContainerView.

In step 5, the example code is missing the FrameLayout tag starter, it has <xmlns:... vs <FrameLayout xmlns:...

Additionally, in step 5, app:navGraph="@navigation/nav_graph" results in an error (Cannot resolve symbol) which is cleared up in the next section (Set Up The Navigation Graph) but it would follow the previous instances where the editor raised an error if it mentioned it in the step itself, i.e. 'The editor will claim this symbol isn't resolved, but don't worry, we'll address that in the next step.'

**Comment by jtavva** [comment]
@adalius 
Thank you so much for reporting this issue. This is fixed and will be published soon.
