### ISSUE TITLE
Android Basics: Fragments Navigation component

### ISSUE THREAD

**Issue by silvercub** [google-developer-training/android-basics-kotlin-words-app#144]
**URL of codelab**

https://developer.android.com/codelabs/basic-android-kotlin-training-fragments-navigation-component

**In which task and step of the codelab can this issue be found?**

Step 1 "Before you" begin

**Describe the problem**

Minor typo toward the end of the third paragraph. instead of "fragmen" it should be "fragment".

**Steps to reproduce?**
1. Start the codelab
2. Scroll down to the third paragraph which is after the phone/contacts picture and right before the second picture on the page.
3. The typo is at the end of the second to last sentence in the paragraph.

**Versions**
_Android Studio version:_ N/A
_API version of the emulator:_ N/A 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by calren** [comment]
Thanks for filing! This should now be fixed
