### ISSUE TITLE
Android Basics: Activities and intents

### ISSUE THREAD

**Issue by paladaxar** [google-developer-training/android-basics-kotlin-words-app#146]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-activities-intents?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-3-pathway-1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-activities-intents#6

**In which task and step of the codelab can this issue be found?**
Task 3 (Activities and intents), step 7 (Set Up Implicit Intent)

**Describe the problem**
Should this...

companion object {
   val LETTER = "letter"
   val SEARCH_PREFIX = "https://www.google.com/search?q="
}

be this...

companion object {
   const val LETTER = "letter"
   const val SEARCH_PREFIX = "https://www.google.com/search?q="
}

Maybe the keyword const can be left out...but I wanted to let you know just in case.

**Comment by calren** [comment]
Thanks for filing! This should now be fixed
