### ISSUE TITLE
Android Basics: Activities and intents

### ISSUE THREAD

**Issue by RawadK** [google-developer-training/android-basics-kotlin-words-app#150]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-activities-intents?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-3-pathway-1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-activities-intents#1

**In which task and step of the codelab can this issue be found?**
Step 6 Under Open the project in Android Studio

**Describe the problem**
After I import the project I cant run the project... the run button is greyed out

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by calren** [comment]
This seems like there was an issue when importing the project itself. I would recommend referencing the documentation for [importing projects](https://developer.android.com/studio/intro/migrate#import_as_a_project)
