### ISSUE TITLE
Android Basics: Activities and intents

### ISSUE THREAD

**Issue by Radionov000** [google-developer-training/android-basics-kotlin-words-app#151]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-activities-intents?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-3-pathway-1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-activities-intents#8

**In which task and step of the codelab can this issue be found?**
in all

**Describe the problem**
If you reduce the width of the browser window, then the "next" button is shifted off the screen down

**Steps to reproduce?**
1. Go to...  the page codelab
2. Click on... 
![1](https://user-images.githubusercontent.com/85954764/125299702-1085b480-e332-11eb-89de-00b27036bb5d.png)
it's ok. but if you reduce the width of the browser window so that the menu on the left of the page disappears then the "next" button is shifted off the screen down
![2](https://user-images.githubusercontent.com/85954764/125300128-69ede380-e332-11eb-8522-f2f407e92308.png)

3. See error...
windows 10, in google chrome browser. 
**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by MeAdarshMishra** [comment]
use version buildToolsVersion "30.0.0"rc4 to fix this error

**Comment by calren** [comment]
This is an issue with the web page / platform itself and not related to this codelab / the code repo, so we'll be closing it for now. A good place to file this potential bug could be the [public issue tracker](https://developers.google.com/issue-tracker)
