### ISSUE TITLE
Android Basics: Fragments Navigation component

### ISSUE THREAD

**Issue by Java-driod** [google-developer-training/android-basics-kotlin-words-app#152]
**URL of codelab**

https://developer.android.com/codelabs/basic-android-kotlin-training-fragments-navigation-component?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-3-pathway-2%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-fragments-navigation-component#7

**In which task and step of the codelab can this issue be found?**
Step 8

**Describe the problem**
It's not that much of a mistake, just something I think you should add. It's just that under the "Use FragmentContainerView in MainActivity" Heading on step 3 we do something that android studio flags as an error. I thought I messed something up earlier when this happens and searched all around for how to fix it. I'm not very experienced and thought there was a problem with the build.gradle or something. It would be helpful, to just put in parenthesis "this will show as an error, which will be addressed in a later step", or something along those lines so the user knows that they aren't doing something wrong. I am aware that this isn't really a bug, but I think it would be beneficial for other usersrs. Thank you so much!

**Steps to reproduce?**
1. Go to...Fragments and the Navigation Component collab
2. Click on...Step 8
3. See error (not really error)... Under the Use FragmentContainerView in MainActivity heading, on the 3rd (& 4th) step

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by osuleymanova** [comment]
@Java-driod 
Thank you for contacting us and sharing your feedback. We have added a message with a note in case of a function failure. Hopefully it will be beneficial.
