### ISSUE TITLE
Android Basics: Activities and intents: Missing DetailActivity

### ISSUE THREAD

**Issue by tuxedotshirt** [google-developer-training/android-basics-kotlin-words-app#154]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-activities-intents?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-3-pathway-1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-activities-intents#4

**In which task and step of the codelab can this issue be found?**
5

**Describe the problem**
The DetailActivity is an unresolved reference and the app won't run

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by Gmatieso** [comment]
Hello, i am following up on this. Just checkin.... was a solution provided? coz i also find DetailActivity missing????

**Comment by viperguynaz** [comment]
make sure you checkout the `starter` branch

**Comment by Gmatieso** [comment]
noted al keep you posted on my progress

**Comment by osuleymanova** [comment]
@tuxedotshirt 
Thank you for reaching out to us. 
Please follow the steps provided in the codelab: after you clone the repo, check out the code from the origin/starter branch.
Happy coding!
