### ISSUE TITLE
Android Basics: Everywhere

### ISSUE THREAD

**Issue by reknoZ** [google-developer-training/android-basics-kotlin-words-app#156]
Using macOS Big Sur 11.1 and its Safari

Trying to follow the Android Basics tutorials (really well designed, by the way!).
I log in.
I get a badge.
I start a pathway / activity.
I get called away from my computer for 10 minutes or an hour or all day.
I come back to the screen that I last saw.
I continue/complete the activity and I'm brought back to the pathway screen.
It *shows* that I'm still logged in, but...... the checkmarks don't appear.
I refresh the page.
No checkmarks and "Sign in"
I sign in and all the checkmarks I did *before* are there, but I have to go *back* into the last activity I completed, see that I'm on the last step, click "Done" and then I see the checkmark for that activity.

<sigh>
I have to do this every day. 2-3 times a day.

Why can't you keep me logged in?

**Comment by calren** [comment]
This repo is contained to issues directly related to the specific codelab. Perhaps a better platform for this would be the [Android Public Issue tracker](https://source.android.com/setup/contribute/report-bugs).

**Comment by reknoZ** [comment]
You're a little quick on the trigger, Caren. The link you provided has nothing to do with the issue I raised. It's not an Android Public thing. It's not related to one specific lesson, it's related to ALL lessons. Is there another place I should post? Something relevant? I'm trying to give feedback on the website. If not here, where should I give feedback?
