### ISSUE TITLE
Android basics: Activities and intents

### ISSUE THREAD

**Issue by qkhms145** [google-developer-training/android-basics-kotlin-words-app#158]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-activities-intents?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-3-pathway-1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-activities-intents#1

**In which task and step of the codelab can this issue be found?**
In starter code lesson step 5

**Describe the problem**
When i open the project this error was shown: "Cause: javax.xml.bind.UnmarshalException
 - with linked exception:
[org.xml.sax.SAXParseException; lineNumber: 1; columnNumber: 460; An invalid XML character (Unicode: 0x0) was found in the element content of the document.]
An invalid XML character (Unicode: 0x0) was found in the element content of the document."
I try resync and rebuild not worked and this file SAXParseException is read only 

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 4.2.2
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by osuleymanova** [comment]
@qkhms145 
Thank you for reaching out to us. Our suggestion is to double check your XML files for an invalid character. If it doesn't help please compare against the solution code (provided at the end of that codelab). And if even this doesn't  work again please reopen the issue with more details and screenshot provided.
