### ISSUE TITLE
Android Basics: Collections

### ISSUE THREAD

**Issue by kev-coding42** [google-developer-training/android-basics-kotlin-words-app#159]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-collections?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-3-pathway-1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-collections#3

**In which task and step of the codelab can this issue be found?**
  Learn about lambdas and higher-order functions ->  Higher-order function -> point 2

**Describe the problem**
  in point 2. It is described that how sortedWith() function works. But when we type that given below code in IDE. It shows
compiler error. Also, from code we can determine that it will produce Int.  But in point 3, we can see that It returns List as an output.

It should be like this:
input :
        val peopleNames = listOf("Fred", "Ann", "Barbara", "Joe")
       val sortedList = peopleNames.sortedWith(compareBy { it.length})
        println(sortedList)

output: [Ann, Joe, Fred, Barbara]

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by calren** [comment]
Which compile error are you seeing? The code should work if you add the line of code 
`println(peopleNames.sortedWith { str1: String, str2: String -> str1.length - str2.length })` in the `main()` function that was provided earlier
