### ISSUE TITLE
Android Basics: Fragments Navigation component

### ISSUE THREAD

**Issue by ivamotelolamounier** [google-developer-training/android-basics-kotlin-words-app#160]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-fragments-navigation-component?hl=pt&continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-3-pathway-2%3Fhl%3Dpt%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-fragments-navigation-component#3

**In which task and step of the codelab can this issue be found?**

Copie o conteúdo do arquivo activity_main.xmlno fragment_letter_list.xmle o conteúdo do activity_detail.xmlno fragment_word_list.xml. Atualize tools:contextno fragment_letter_list.xmlpara .LetterListFragmente tools:contextno fragment_word_list.xmlpara .WordListFragment.

**Describe the problem**
fragment_letter_list.xml

<?xml version="1.0" encoding="utf-8"?>
<FrameLayout xmlns:android="http://schemas.android.com/apk/res/android"
   xmlns:tools="http://schemas.android.com/tools"
   android:layout_width="match_parent"
   android:layout_height="match_parent"
   tools:context=".WordListFragment">

problem is: tools:context should contain the value "".LetterListFragment"" and NOT "".WordListFragment""

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by calren** [comment]
Thanks for filing! This should now be fixed
