### ISSUE TITLE
Android Basics: Activities and intents

### ISSUE THREAD

**Issue by SnehashisWalk** [google-developer-training/android-basics-kotlin-words-app#162]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-activities-intents?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-3-pathway-1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-activities-intents#1

**In which task and step of the codelab can this issue be found?**
In Step 2: Starter Code of the codelab Activities and Intents.

**Describe the problem**
In the github repository the activity_detail.xml line no. 29 the layout should be item_view not word_item_view. (because word_item_view layout does not exists)

Correct code: tools:listitem="@layout/item_view" />

**Steps to reproduce?**
1. Go to...
    https://github.com/google-developer-training/android-basics-kotlin-words-app/blob/starter/app/src/main/res/layout/activity_detail.xml

2. Click on...
    Line 29
3. See error...
    Error code: tools:listitem="@layout/word_item_view" />
    Correct code: tools:listitem="@layout/item_view" />

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._
![image](https://user-images.githubusercontent.com/39059004/129451080-2c98fbd8-4cb7-4d2e-9559-252dd1f3b8df.png)

**Comment by calren** [comment]
Thanks for filing! This has now been fixed
