### ISSUE TITLE
Android Basics: Activities and intents

### ISSUE THREAD

**Issue by Germanicus1982** [google-developer-training/android-basics-kotlin-words-app#163]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-activities-intents?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-3-pathway-1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-activities-intents#5

**In which task and step of the codelab can this issue be found?**
Every step

**Describe the problem**
I believe the downloaded sample code is actually the finished code for the whole unit. When trying to follow along my first indication was on step 5, when I looked in the code provided there was a solution already there and it was vastly different than what was expected to be put in there (setOnClickListener() code for reference). On step 6 my suspicions were confirmed when DetailActivity is nowhere to be found in the project. I'm guessing this is replaced later in the series by the fragments currently in the downloaded code.

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by osuleymanova** [comment]
@Germanicus1982 
Thank you for contacting us. Please follow the steps hot to download the starter code provided in the codelab:
https://android.devsite.corp.google.com/codelabs/basic-android-kotlin-training-activities-intents#1
You may also refer to the comment of @blonkm.
