### ISSUE TITLE
Android Basics: Fragments Navigation component

### ISSUE THREAD

**Issue by crave503** [google-developer-training/android-basics-kotlin-words-app#164]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-fragments-navigation-component?authuser=1&continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-3-pathway-2%3Fauthuser%3D1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-fragments-navigation-component#0

**In which task and step of the codelab can this issue be found?**
1. Before you begin

**Describe the problem**
Typo: "...contained in a separate fragmen."

**Steps to reproduce?**
Read the page

**Comment by calren** [comment]
Thanks for filing! This should now be fixed
