### ISSUE TITLE
Android Basics: Activities and intents

### ISSUE THREAD

**Issue by golfcalcs** [google-developer-training/android-basics-kotlin-words-app#165]
**URL of codelab**

**In which task and step of the codelab can this issue be found?**

**Describe the problem**

Activities and Intents – Solution code does not have a DetailActivity.kt which is mentioned repeatedly in modules 2 to 10. Any chance of producing sample code with the Detail Activity as per modules 1 to 10. Thanks Wendel
  

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by blonkm** [comment]
After getting the main branch you need to get the starter branch:

1. Git > Branches
2. Origin > starter > checkout

choose force checkout
