### ISSUE TITLE
Android Basics: Fragments Navigation component

### ISSUE THREAD

**Issue by Lehaem** [google-developer-training/android-basics-kotlin-words-app#167]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-fragments-navigation-component?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-3-pathway-2%3Fhl%3Den%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-fragments-navigation-component&hl=en#0

**In which task and step of the codelab can this issue be found?**
Text of the "1. Before you begin"

**Describe the problem**
Misprint "each be contained in a separate fragme**n.**"

**Steps to reproduce?**
1. Go to URL of codelab
2. See misprint in the "1. Before you begin"

**Versions**
NA

**Additional information**
![image](https://user-images.githubusercontent.com/35835390/130755126-654a5c62-45ae-4b40-944f-421ac73d941c.png)

**Comment by calren** [comment]
Thanks for filing! This should now be fixed
