### ISSUE TITLE
Android Basics: Fragments Navigation component

### ISSUE THREAD

**Issue by JesyNoelia** [google-developer-training/android-basics-kotlin-words-app#168]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-fragments-navigation-component?hl=es&continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-3-pathway-2%3Fhl%3Des%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-fragments-navigation-component#3

**In which task and step of the codelab can this issue be found?**
Task 4

**Describe the problem**
I think there is an error in the code shown in the codelab. 
Where we have to update tools:context. in both fragments, appear:  tools:context=".WordListFragment". 
I think that for the LetterListFragment, we have to set the context to ".LetterListFragment"
![error](https://user-images.githubusercontent.com/81963107/130787819-bf5c1722-028f-4320-8cdb-a96ba898404e.png)

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by calren** [comment]
Thanks for filing! I believe this is now fixed.
