### ISSUE TITLE
Android Basics: Activities and intents: Needs clarification on needed imports

### ISSUE THREAD

**Issue by dm36** [google-developer-training/android-basics-kotlin-words-app#170]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-activities-intents?hl=en&continue=https%3A%2F%2Fcodelabs.developers.google.com%2F%3Fcat%3Dandroid#6

**In which task and step of the codelab can this issue be found?**
Steps 5-9

**Describe the problem**
The documentation lacks info about the imports needed to run the app. I walked through the steps and when I clicked run- the project failed because several imports were missing (import android.content.Intent, import android.net.Uri etc). Each step should mention an import if needed for the app to run.

**Versions**
_Android Studio version:_ Arctic Fox 2020.3.1
_API version of the emulator:_ Pixel 5 API 30

**Comment by osuleymanova** [comment]
@dm36 
Thank you for reaching out to us and sharing your feedback. How to enable auto imports, please refer to the codelab:
https://developer.android.com/codelabs/basic-android-kotlin-training-create-dice-roller-app-with-button?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-four%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-create-dice-roller-app-with-button#3.

![Screen Shot 2022-09-22 at 4 43 42 PM](https://user-images.githubusercontent.com/86437155/191869818-033bf3fd-501e-462b-bd0f-b75427d1f199.png)
