### ISSUE TITLE
Android Basics: Fragments Navigation component

### ISSUE THREAD

**Issue by KaungZM** [google-developer-training/android-basics-kotlin-words-app#171]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-fragments-navigation-component?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-3-pathway-2%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-fragments-navigation-component#6

**In which task and step of the codelab can this issue be found?**
NavHost section, Line 8 of "7. Jetpack Navigation Component"

**Describe the problem**
typo: "A NavHost is used to display destinations **form** a navigation graph within an activity."
It should be "from" not "form"

**Steps to reproduce?**
1. Go to URL of codelab
2. See misprint in the NavHost section, Line 8 of "7. Jetpack Navigation Component"

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
![Screenshot 2021-09-05 201242](https://user-images.githubusercontent.com/50942485/132129107-af46519d-4372-44f7-883f-728fe5344b35.png)

**Comment by calren** [comment]
Thanks for filing! This should now be fixed
