### ISSUE TITLE
Android Basics: Fragments Navigation component

### ISSUE THREAD

**Issue by PhilBlaisDev** [google-developer-training/android-basics-kotlin-words-app#172]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-fragments-navigation-component?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-3-pathway-2%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-fragments-navigation-component#0

**In which task and step of the codelab can this issue be found?**
1. Before you begin

**Describe the problem**

Just a small typo to the word 'Fragment', there's a missing 't'

[...]"below, both the navigation UI on the left and the content on the right can each be contained in a separate fragmen."

**Steps to reproduce?**
1. Go to the provided Codelab URL
2. in the third paragraph of the **Before you begin** section 
3. typo in the word fragment as stated in the **Describe the problem** of this report

**Comment by calren** [comment]
Thanks for filing! This has now been fixed
