### ISSUE TITLE
Android Basics: Fragments Navigation component

### ISSUE THREAD

**Issue by ArpitChhabra** [google-developer-training/android-basics-kotlin-words-app#174]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-fragments-navigation-component?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-3-pathway-2%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-fragments-navigation-component#6

**In which task and step of the codelab can this issue be found?**
Point number 2, line 1. It says "NavHost: A NavHost is used to display destinations **form** a navigation graph within an activity."

**Describe the problem**
As you already may have noticed in the above issue it says form not from. fix it

**Comment by calren** [comment]
Thanks for filing! This is now fixed
