### ISSUE TITLE
Android Basics: Fragments Navigation component

### ISSUE THREAD

**Issue by k-andy** [google-developer-training/android-basics-kotlin-words-app#175]
Typo in the text

https://developer.android.com/codelabs/basic-android-kotlin-training-fragments-navigation-component?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-3-pathway-2%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-fragments-navigation-component#0

Task "Fragments and the Navigation Component", step "1. Before you begin"

There is a typo in text - "fragmen" instead of "fragments". Full sentence "In the example below, both the navigation UI on the left and the content on the right can each be contained in a separate fragmen.". See attached screenshot

**Steps to reproduce?**
1. Go to https://developer.android.com/codelabs/basic-android-kotlin-training-fragments-navigation-component?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-3-pathway-2%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-fragments-navigation-component#0
2. Scroll to the explanation about fragments

<img width="1206" alt="Screenshot 2021-09-07 at 15 05 20" src="https://user-images.githubusercontent.com/2077743/132350295-6e3aa991-d7ea-4018-b881-5626dc52aa8f.png">

**Comment by calren** [comment]
Thanks for filing! This has nowo been fixed
