### ISSUE TITLE
Android Basics: Fragments Navigation component

### ISSUE THREAD

**Issue by imahmwd14** [google-developer-training/android-basics-kotlin-words-app#18]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-fragments-navigation-component?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-3-pathway-2%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-fragments-navigation-component#4

**In which task and step of the codelab can this issue be found?**
The 5th

**Describe the problem**
It is written that the binding classes are generated automatically by Android Studio, but what's failed to be mentioned is that Android Studio generates those classes only after the viewBinding property in the buildFeatures has been enabled by being set to true!

**Steps to reproduce?**
just go the 5th step of the codelab and read it

**Comment by jtavva** [comment]
@imahmwd14 
Thank you so much for reporting this issue. This is fixed and will be published soon.
