### ISSUE TITLE
Android Basics: Activities and intents

### ISSUE THREAD

**Issue by mburdett555** [google-developer-training/android-basics-kotlin-words-app#180]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-activities-intents?hl=en&continue=https%3A%2F%2Fcodelabs.developers.google.com%2F%3Fcat%3Dandroid%26authuser%3D4%231#1

**In which task and step of the codelab can this issue be found?**
Download the Starter Code for this Codelab

**Describe the problem**
It is not clear how to download the starter code.
I have followed the steps, it downloads a zip file "android-basics-kotlin-words-app-main"
This is _not_ the starter code (despite be in the starter branch assuming by the codelab instructions).
The project downloaded does not have "detail activity" and has fragments in its place
Therefore the github starter code is unusable because it doesnt match the instructions in the codelab.

**Steps to reproduce?**
Go to the codelab
Download the github starter code as per the codelab instructions
Open the project in android studio and follow the next steps in the codelab 
(https://developer.android.com/codelabs/basic-android-kotlin-training-activities-intents?hl=en&continue=https%3A%2F%2Fcodelabs.developers.google.com%2F%3Fcat%3Dandroid%26authuser%3D4%231#2)
It refers to a screenshot with "DetailActivity" on it. This is not in the project downloaded from github,

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._
![image](https://user-images.githubusercontent.com/32547357/134165692-638897d5-7004-4fa8-8f87-b9d420b015df.png)
![image](https://user-images.githubusercontent.com/32547357/134165740-89ae4945-c464-49b2-8043-92ed09a36df6.png)

**Comment by calren** [comment]
This seems like an issue with Github that has now been fixed (the issue was the attempting to download a zip of a branch was instead downloading a zip of the main branch). I've tried download the zip file of the starter branch and confirmed it was not the completed app.
