### ISSUE TITLE
Android Basics: Activities and intents

### ISSUE THREAD

**Issue by Kennedy-Chidi** [google-developer-training/android-basics-kotlin-words-app#181]
**URL of codelab**

**In which task and step of the codelab can this issue be found?**
All the steps

**Describe the problem**
After following the instructions to get the clone of the starter project, on lunching in my android studio I realized that the files are different from the one used in the codelab. In fact it is the finished version of the codelab with a lot of cold different from the ones written in the codelab. Hence I couldn't follow up. So please do some updates for the intents tutorial thanks

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by calren** [comment]
This seems like an issue with Github that has now been fixed (the issue was the attempting to download a zip of a branch was instead downloading a zip of the `main` branch). I've tried download the zip file of the starter branch and confirmed it was not the completed app.
