### ISSUE TITLE
Android Basics: Activities and intents Not Starter but Main Folder

### ISSUE THREAD

**Issue by Hiwoyn** [google-developer-training/android-basics-kotlin-words-app#183]
**URL of codelab**

**In which task and step of the codelab can this issue be found?**
Can't find Starter folder

**Describe the problem**

I download the zip "When you download the starter code from GitHub, note that the folder name is android-basics-kotlin-words-app-starter. Select this folder when you open the project in Android Studio.".
But I can't find any starter folder

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by calren** [comment]
This seems like an issue with Github where the main branch was being downloaded as a zip instead of the `starter` branch. The issue has now been fixed. I've tried download the zip file of the starter branch and confirmed it was not the completed app.
