### ISSUE TITLE
Android Basics: Activities and intents

### ISSUE THREAD

**Issue by JicaLou** [google-developer-training/android-basics-kotlin-words-app#184]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-activities-intents?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-3-pathway-1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-activities-intents#2

**In which task and step of the codelab can this issue be found?**
task 2, task 3 

**Describe the problem**
Greetings, the code provided to work with the codelab (Intents and activities) does not conform to the structure shown to work

**Steps to reproduce?**
1.- Go to task 2 
2.- download and import the project from (URL: https://github.com/google-developer-training/android-basics-kotlin-words-app/tree/starter)
3.- See the strcuture in app>java>com.example.wordsapp 
Works with classes LeeterListFragment and WordListFragment

4.- Go to task 3 
The codelab works with class DetailActivity

**Versions**
_Android Studio version:_ 11.0.10 (Arctic Fox 2020.3.1)
_API version of the emulator:_ 

**Additional information*
![Code provided](https://user-images.githubusercontent.com/90061368/134352997-1a4bafe4-122e-4cee-84bb-66e389a2cc3c.jpg)
![Codelab](https://user-images.githubusercontent.com/90061368/134353014-a67b8ae4-ad73-402d-9142-9049f36e2f1c.jpg)
*

**Comment by Hiwo21400** [comment]
Same

**Comment by Hiwo21400** [comment]
Or we are doing something wrong.

**Comment by calren** [comment]
This seems like an issue with Github that has now been fixed. I've tried download the zip file of the starter branch and confirmed it was not the completed app. And thanks @TF-IT1 for helping with a workaround
