### ISSUE TITLE
Android Basics: Activities and intents

### ISSUE THREAD

**Issue by Swarandeep1** [google-developer-training/android-basics-kotlin-words-app#185]
**URL of codelab**

**In which task and step of the codelab can this issue be found?**

In step 3, when reviewing the package I found that there were a file missing and extra files not called out in the original git page.  After further investigation I found that the git location: https://github.com/google-developer-training/android-basics-kotlin-words-app.git has different files in the src/main directory than what is called out in the training module.  No matter if I download the zip or do a git clone of the location provided on the git page, I will not get the same package described in the training module.

**Describe the problem**

**Steps to reproduce?**
1. Go to step 2 of the training module,
2. Click on the link to the git page
3. Click the Green Code dropdown and select download zip
4. extract zip and open with Android Studio
5. navigate to main directory, 
6. you will see there is a different set of files.

**Versions**
_Android Studio version: Arctic Fox 3.1
_API version of the emulator: not sure where to look for that

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

I think the link to the git page is not the starter location.

**Comment by PhenixFine** [comment]
Here's a link to the zip file itself:
https://github.com/google-developer-training/android-basics-kotlin-words-app/archive/refs/heads/starter.zip
They do have the right link up to the starter branch, but once there it's easy to accidentally switch to the main branch ( though it could also be something they recently fixed ).

**Comment by calren** [comment]
This seems like an issue with Github that has now been fixed. I've tried download the zip file of the starter branch and confirmed it was not the completed app.
