### ISSUE TITLE
Android Basics: Activities and intents

### ISSUE THREAD

**Issue by fdcl97** [google-developer-training/android-basics-kotlin-words-app#186]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-activities-intents?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-3-pathway-1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-activities-intents#1

**In which task and step of the codelab can this issue be found?**
Step 2

**Describe the problem**
When downloading the project, git gives you the completed codelab instead of the started project. A lot of people have reported the same problem, but no one helps us, there is no such "started branch"

**Steps to reproduce?**
1. Download the zip provided by git/clone the project.

**Versions**
_Android Studio version:_  4.1
_API version of the emulator:_

**Comment by PhenixFine** [comment]
If you are downloading it, make sure you have the starter branch selected ( I just did a test download and I got the starter branch ). Here's the link to the starter branch:
https://github.com/google-developer-training/android-basics-kotlin-words-app/tree/starter
If you forked it, you have to switch to the starter branch manually ( there doesn't seem to be a way to fork a specific branch ).

**Comment by fdcl97** [comment]
I do not know what happened, I opened the link from the codelab and made
sure I was on "started branch", but by downloading the zip or cloning it,
the project was the completed words app, including fragments. Many people
have the same problem, when I read the issues on the website, almost every
post was about that problem. Thank you, from the link in this email, y
could get the correct project

**Comment by calren** [comment]
This seems like an issue with Github that has now been fixed. I've tried download the zip file of the `starter` branch and confirmed it was not the completed app.
