### ISSUE TITLE
Android Basics: Activities and intents

### ISSUE THREAD

**Issue by dvivancoch** [google-developer-training/android-basics-kotlin-words-app#188]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-activities-intents?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-3-pathway-1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-activities-intents#9

**In which task and step of the codelab can this issue be found?**
When downloading the starter project

**Describe the problem**

The content of the downloaded zip is not from starter branch. 

After clicking the github link and doing step 3 in code lab, the downloaded zip is a main branch project.

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

![image](https://user-images.githubusercontent.com/60155600/134611329-d2b5b7dd-7b7c-43b4-8afc-30c44e125ca1.png)
![image](https://user-images.githubusercontent.com/60155600/134611377-fee75005-9dde-40cd-8f98-4faa47998d7a.png)
![image](https://user-images.githubusercontent.com/60155600/134611425-e6635e54-62a8-4f63-88b4-9dbf3365a089.png)

**Comment by PhenixFine** [comment]
looks like you downloaded the main branch. Here's the link to the starter branch:
https://github.com/google-developer-training/android-basics-kotlin-words-app/tree/starter
And when you download it the filename should look like this:
android-basics-kotlin-words-app-starter.zip

**Comment by calren** [comment]
Thanks @PhenixFine for helping solve the confusion! Since there's no actionable task and things are working as expected, we'll be closing this issue now.
