### ISSUE TITLE
Android Basics: Activities and intents: Missing detail activity

### ISSUE THREAD

**Issue by kerosene98** [google-developer-training/android-basics-kotlin-words-app#189]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-activities-intents?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-3-pathway-1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-activities-intents#4

**In which task and step of the codelab can this issue be found?**
Task 5

**Describe the problem**

The task describes setting up explicit intent and the class DetailActivity is already implemented. However following steps 1,2, and 3. The DetailActivity class is not found and is required to be created. It seems the code from Git is maybe not aligned to the codelab original version maybe? Without doing any modifications to the code base the code seems to work functionally. Its adding the code from the codelab which breaks the app.

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...
Error is DatialActivity is not available. 

**Versions**
_Android Studio version:_ 
Arctic Fox 2020.3.1 Patch 2
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._
     /**
     * Replaces the content of an existing view with new data
     */
    override fun onBindViewHolder(holder: LetterViewHolder, position: Int) {
        val item = list.get(position)
        holder.button.text = item.toString()

        // Assigns a [OnClickListener] to the button contained in the [ViewHolder]
        holder.button.setOnClickListener {

            val context = holder.view.context   << added
            val intent = Intent(context, DetailActivity::class.java)   << added
            intent.putExtra("letter", holder.button.text.toString())  << added
            context.startActivity(intent)   << added
            
            // Create an action from WordList to DetailList
            // using the required arguments
            val action = LetterListFragmentDirections.actionLetterListFragmentToWordListFragment(letter = holder.button.text.toString())
            // Navigate using that action
            holder.view.findNavController().navigate(action)
        }
    }

**Comment by calren** [comment]
DetailActivity should be present in the `starter` branch of the repo. 

(It is not present, however, in the `main` branch. It might be helpful to check that you were on the `starter` branch when working through the codelab)
