### ISSUE TITLE
Android Basics: Activities and intents

### ISSUE THREAD

**Issue by Jason627592** [google-developer-training/android-basics-kotlin-words-app#19]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-activities-intents?hl=en&continue=https%3A%2F%2Fcodelabs.developers.google.com%2F#0

**In which task and step of the codelab can this issue be found?**
In task 6, step 5-6

companion object {
   val LETTER = "letter"
   val SEARCH_PREFIX = "https://www.google.com/search?q="
}
val queryUrl: Uri = Uri.parse("${DetailActivity.SEARCH_PREFIX}${item}")

**Describe the problem**
In the above two steps, it requires to change the string "https://www.google.com/search?q=" into a constant. However, the variable in step 6 (queryUrl) haven't exist in this step. I think it should put after Task 7 (Setting up the intent).

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by MisterAlea** [comment]
I experienced the same issue.

**Comment by wazo-byte** [comment]
i dont know how to fix this. i opened the git hub and ctrl + c ctrl + v since the code in the android app doesn't have setOnClickListener but i dont know how to fix that Uri error
![Words – WordAdapter kt  Words app  Android Studio 1_2_2021 1_03_43 PM](https://user-images.githubusercontent.com/76853381/103451146-6a5e4f80-4cfb-11eb-9d3e-151d67421d1f.png)

**Comment by wazo-byte** [comment]
> i dont know how to fix this. i opened the git hub and ctrl + c ctrl + v since the code in the android app doesn't have setOnClickListener but i dont know how to fix that Uri error
> ![Words – WordAdapter kt Words app Android Studio 1_2_2021 1_03_43 PM](https://user-images.githubusercontent.com/76853381/103451146-6a5e4f80-4cfb-11eb-9d3e-151d67421d1f.png)

never mind i fixed it

**Comment by jtavva** [comment]
@MisterAlea 
@Jason627592 
Thank you so much for reporting this issue. This is fixed and will be published soon.
