### ISSUE TITLE
Android Basics: Activities and intents

### ISSUE THREAD

**Issue by mziyadam** [google-developer-training/android-basics-kotlin-words-app#190]
https://developer.android.com/codelabs/basic-android-kotlin-training-activities-intents?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-3-pathway-1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-activities-intents#8

![image](https://user-images.githubusercontent.com/64635497/135376824-88de87c8-e59e-4316-aa1d-268c280e0ace.png)

is this 'if' right?

because 'if (isLinearLayoutManager)
           ContextCompat.getDrawable(this, R.drawable.ic_grid_layout)' will return grid icon

cmiiw

**Comment by calren** [comment]
Good catch! The two blocks should be swapped, and we've fixed this in the codelab. Thanks for filing!
