### ISSUE TITLE
Android Basics: Collections: Typo in Task 4

### ISSUE THREAD

**Issue by louislefevre** [google-developer-training/android-basics-kotlin-words-app#193]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-collections#3

**In which task and step of the codelab can this issue be found?**
Task 4, `Higher-order functions` section, step 3.

**Describe the problem**
Slight typo in the sentence `That matches what it is needed for sorting`, should be `That matches what is needed for sorting` or something similar.

**Comment by calren** [comment]
thanks for filing! this is now fixed
