### ISSUE TITLE
Android Basics: Fragments Navigation component

### ISSUE THREAD

**Issue by louislefevre** [google-developer-training/android-basics-kotlin-words-app#195]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-fragments-navigation-component#0

**In which task and step of the codelab can this issue be found?**
Task 1, `Before you begin` section.

**Describe the problem**
The sentence `...can each be contained in a separate fragmen.` has a typo - "fragment" is misspelled as "fragmen".

**Comment by calren** [comment]
this has now been fixed, thanks for filing!
