### ISSUE TITLE
Android Basics: Fragments Navigation component: Unable to build project after 'Setting the Start Destination' step

### ISSUE THREAD

**Issue by dvmatias** [google-developer-training/android-basics-kotlin-words-app#198]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-fragments-navigation-component?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-3-pathway-2%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-fragments-navigation-component#7

**In which task and step of the codelab can this issue be found?**
Setting the Start Destination

**Describe the problem**
In the last sentence of the section the codelab  says _"...At this point, **go ahead and build the project**. This will..."_. The problem is that LetterAdapter.kt is still creating an explicit intent using DetailActivity class and the compiler end up throwing an error. You should warning to students about this expected error or just to not encourage them to build the project yet.

**Steps to reproduce?**
1. Compile the project

**Comment by rajitk13** [comment]
$ adb shell am start -n "com.example.wordsapp/com.example.wordsapp.MainActivity" -a android.intent.action.MAIN -c android.intent.category.LAUNCHER
Unexpected error while executing: am start -n "com.example.wordsapp/com.example.wordsapp.MainActivity" -a android.intent.action.MAIN -c android.intent.category.LAUNCHER
Error while Launching activity


I am also getting an error and above is the error code corresponding to it.
