### ISSUE TITLE
Android Basics: Fragments Navigation component

### ISSUE THREAD

**Issue by chcliu** [google-developer-training/android-basics-kotlin-words-app#199]
[**URL of codelab**](https://developer.android.com/codelabs/basic-android-kotlin-training-fragments-navigation-component?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-3-pathway-2%3Fauthuser%3D1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-fragments-navigation-component&authuser=1#6)

**In which task and step of the codelab can this issue be found?**
In _Jetpack Navigation Component_ section of **Fragments and the Navigation Component**

**Describe the problem**
Typo 
> NavHost: A NavHost is used to display destinations _**form**_ a navigation graph within an activity. When you navigate between fragments, the destination shown in the NavHost is updated. You'll use a built-in implementation, called NavHostFragment, in your MainActivity.

**Comment by calren** [comment]
This has now been fixed, thanks for filing!
