### ISSUE TITLE
Android Basics: Activities and intents

### ISSUE THREAD

**Issue by humbleharry1234** [google-developer-training/android-basics-kotlin-words-app#20]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-activities-intents?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-3-pathway-1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-activities-intents#5

**In which task and step of the codelab can this issue be found?**
Task 6, step 5

**Describe the problem**
Implicit intent has not yet been set up. Possibly this ection should come after task 7

**Steps to reproduce?**
1. Go to... URL linked above
2. Click on...  Task 6 on the side menu
3. See error...  In step 5

**Versions**
Not a version issue, issue with the task itself

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by jtavva** [comment]
@humbleharry1234 
Thank you so much for reporting this issue. This is fixed and will be published soon.
