### ISSUE TITLE
Android Basics: Fragments Navigation component

### ISSUE THREAD

**Issue by Santiago-Monta** [google-developer-training/android-basics-kotlin-words-app#201]
**URL of codelab**

https://developer.android.com/codelabs/basic-android-kotlin-training-fragments-navigation-component?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-3-pathway-2%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-fragments-navigation-component#4

**In which task and step of the codelab can this issue be found?**

"Tu turno" 

**Describe the problem**

1 Copia el objeto complementario de DetailActivity a WordListFragment. Asegúrate de que la referencia a **_SEARCH_PREFIX_** en **WordAdapter** se haya actualizado de modo que haga referencia a WordListFragment.

1 Copia el objeto complementario de DetailActivity a WordListFragment. Asegúrate de que la referencia a **_intent.putExtra_** en **_LetterAdapter_** se haya actualizado de modo que haga referencia a WordListFragment.

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by viperguynaz** [comment]
make sure you checkout the `starter` branch
