### ISSUE TITLE
Android Basics: Activities and intents, Starter branch missing @layout/word_item_view

### ISSUE THREAD

**Issue by shawn-fetanat** [google-developer-training/android-basics-kotlin-words-app#204]
**URL of codelab**
https://github.com/google-developer-training/android-basics-kotlin-words-app/blob/starter/app/src/main/res/layout/activity_detail.xml

**In which task and step of the codelab can this issue be found?**

```diff
<androidx.recyclerview.widget.RecyclerView
        android:id="@+id/recycler_view"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:clipToPadding="false"
        android:padding="16dp"
-      tools:listitem="@layout/word_item_view" />
+     tools:listitem="@layout/item_view" />
```

**Describe the problem**
`word_item_view` does not exist in `res>layout`. It should be `@layout/item_view` not `@layout/word_item_view`

**Comment by calren** [comment]
Thanks for filing! This should be fixed in https://github.com/google-developer-training/android-basics-kotlin-words-app/pull/209

**Comment by shawn-fetanat** [comment]
Btw, there's a few things missing from the lunch-tray-app. I tried submitting a pull request with the changes but it wouldn't go through. It says "Missing CLA from one or more contributors." I signed up for CLA at the link but it says I have to ask a repo manager to rescan the PR.

Repo: [https://github.com/google-developer-training/android-basics-kotlin-lunch-tray-app](https://github.com/google-developer-training/android-basics-kotlin-lunch-tray-app)

Issues:
- In `activity_main.xml` the ConstraintLayout is missing tools:context=".MainActivity"
- In `NavigationTest.kt` all instances of `startOrder` need to be changed to `startOrderFragment`
- In `EntreeMenuFragment`, `SideMenuFragment`, `AccompanimentMenuFragment`, and `CheckoutFragment` the `override fun onCreate(savedInstanceState)` method is unnecessary and can be removed because it's not adding anything new to the inheritted method. I suppose it could be left in there for eductional purposes but it might be helpful to leave comment mentioning that it's not necessary and can be removed.

Lastly, I'm not 100% sure I did everything correctly but I'm pretty sure I did. I passed all tests except for `radio_buttons_update_entree_menu_subtotal` and `radio_buttons_update_accompaniment_menu_subtotal`.

Error for `radio_buttons_update_entree_menu_subtotal`: 

`androidx.test.espresso.base.DefaultFailureHandler$AssertionFailedWithCauseError: 'with text: a string containing "Subtotal: $3.00"' doesn't match the selected view.
Expected: with text: a string containing "Subtotal: $3.00"`

 Error for `radio_buttons_update_accompaniment_menu_subtotal`:
 
 `androidx.test.espresso.base.DefaultFailureHandler$AssertionFailedWithCauseError: 'with text: a string containing "Subtotal: $1.00"' doesn't match the selected view.
Expected: with text: a string containing "Subtotal: $1.00"`

I don't know if you caught that but it looks like the issue seems to be that it's adding an extra ' after the subtotal which doesn't really make sense to me because that test runs `containsString()` and it clearly shows that it does contain that string.

The reason why I think it's an issue with the test is because all other tests including the test for  `radio_buttons_update_entree_menu_subtotal` pass and when I manually test my app everything seems to work correctly.

Oh also, I had a question how come in this codelab: [https://developer.android.com/codelabs/basic-android-kotlin-training-livedata?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-3-pathway-3%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-livedata#6](https://developer.android.com/codelabs/basic-android-kotlin-training-livedata?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-3-pathway-3%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-livedata#6)

...they have us change the `FragmentBinding` to `DataBindingUtil` but in subsequent codelabs it's not used. Just thought that was a little confusing and could possibly use clarification about when it's necessary to use and when it's not.

**Comment by shawn-fetanat** [comment]
Here is my finished app if you want to check it out: [https://github.com/shawn-fetanat/kotlin-completed-lunch-tray-app](https://github.com/shawn-fetanat/kotlin-completed-lunch-tray-app)
