### ISSUE TITLE
Android Basics: Activities and intents

### ISSUE THREAD

**Issue by fredericderu** [google-developer-training/android-basics-kotlin-words-app#21]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-activities-intents

**In which task and step of the codelab can this issue be found?**
Step 8 : Set Up Menu and Icons

**Describe the problem**

The text : .... and "view agenda" (name it ic_linear_layout).

Should read :  .... and "view List" (name it ic_linear_layout).

**Steps to reproduce?**
NA

**Versions**
_Android Studio version:_ 4.1.1
_API version of the emulator:_ 29

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by jtavva** [comment]
@fredericderu 
Thank you so much for reporting this issue. This is fixed and will be published soon.
