### ISSUE TITLE
Android Basics: Fragments Navigation component

### ISSUE THREAD

**Issue by Anees-Iqbal** [google-developer-training/android-basics-kotlin-words-app#213]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-fragments-navigation-component?authuser=1&continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-3-pathway-2%3Fauthuser%3D1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-fragments-navigation-component#0

**In which task and step of the codelab can this issue be found?**
It's the first step, "Before you begin".

**Describe the problem**
It's a typo. In the second sentence of the 3rd paragraph, there is a missing "t" at the end of the word fragment.

**Steps to reproduce?**
1. Go to... Fragments and the Navigation Component codelab first step.
2. Scroll to... 3rd paragraph of the first step.
3. See error... at second sentence's end. "t" is missing in word fragment.

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
<img width="500" alt="Screen Shot 2021-11-10 at 1 23 31 AM" src="https://user-images.githubusercontent.com/56187301/140998958-15556c40-7be2-47f8-9e3a-f48192931b26.png">

**Comment by osuleymanova** [comment]
@Anees-Iqbal 
Thank you for reaching out to us. The typo is fixed and published.
