### ISSUE TITLE
Android Basics: Activities and intents - Git commands to use the starters branch

### ISSUE THREAD

**Issue by migueldiez** [google-developer-training/android-basics-kotlin-words-app#22]
**URL of codelab**

https://developer.android.com/codelabs/basic-android-kotlin-training-activities-intents

(and others)

**In which task and step of the codelab can this issue be found?**

In the "Get the code" section(s) it mentions to download the github code in zip. 

**Describe the problem**

I fetched the code using "git clone". This the usual way. It is not natural to fetch code from github using zip (!!). I realized that the examples are using the "DetailActivity.kt", which is not the "main" branch. 

Of course, you can point to the other branch, but this is not obvious for the novice or the fast reader.

Please, make sure the examples are in sync with the "main" branch or indicate short instructions to point to a specific branch otherwise (e.g.: `git clone <repo>` & `git checkout -t origin/starter`) . 

Example:
``
**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by jtavva** [comment]
@migueldiez 
Thank you so much for reporting this issue. This is fixed and will be published soon.
