### ISSUE TITLE
Android Basics: Activities and intents

### ISSUE THREAD

**Issue by vipulchaudhary16** [google-developer-training/android-basics-kotlin-words-app#224]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-activities-intents?authuser=1&continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-3-pathway-1%3Fauthuser%3D1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-activities-intents#4

**In which task and step of the codelab can this issue be found?**
at the step 3 , 
_Create an Intent, passing in the context, as well as the class name of the destination activity._
`val intent = Intent(context, DetailActivity::class.java)`

**Describe the problem**

In this step, we are setting the class name of the destination activity.
as given a code in Codelab there is **DetailActivity** as a destination activity class but in the starter code provided by you there is no class named **DetailActivity**, We have to replace the **DetailActivity** with **MainActivity** as MainActivity is the class name which you have provided in the starter code.

do changes as below to get rid of the error
`val intent = Intent(context, MainActivity::class.java)`

**Steps to reproduce?**
1. Go to...   `val intent = Intent(context, DetailActivity::class.java)`
2. Click on... DetailActivity
3. See error... Unresolved reference: DetailActivity

**Versions**
_Android Studio version:_  2020.3.1
_API version of the emulator:_ 31

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

When it was DetailActivity

![image](https://user-images.githubusercontent.com/77090657/145399390-89c21f0e-eefd-4a04-ac8f-8559afdc353c.png)

When it is MainActivity

![image](https://user-images.githubusercontent.com/77090657/145399709-a1fa189b-9f82-4f0d-a188-9009dbc67260.png)

**Comment by ShahsTestingZone** [comment]
Add this to letter Adapter. 
import android.content.Intent

**Comment by viperguynaz** [comment]
make sure you checkout the `starter` branch

**Comment by osuleymanova** [comment]
@vipulchaudhary16 
Thank you for reaching out to us. 
Please follow the steps provided in the codelab: after you clone the repo, check out the code from the origin/starter branch.
Happy coding!
