### ISSUE TITLE
Missing Test snippet in Task 6 of description

### ISSUE THREAD

**Issue by SchmittAndre** [google-developer-training/android-basics-kotlin-words-app#228]
**URL of codelab**
?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-3-pathway-2%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fandroid-basics-kotlin-test-navigation-components#5

**In which task and step of the codelab can this issue be found?**
Task 6

**Describe the problem**
missing Code snippet of compleeded test.
"Your test should look something like this:" -> no code

should look like this

"Your test should look something like this:
//CODESNIPPET//"

**Steps to reproduce?**
1. to to Tesk 6
2. Scroll to the bottom
3. See error

**Versions**
-no needed-

**Additional information**
-no needed-

**Comment by osuleymanova** [comment]
@SchmittAndre 
Thank you for reaching out to us. The issue is fixed and will be published soon:


![Screen Shot 2022-06-14 at 4 06 31 PM](https://user-images.githubusercontent.com/86437155/173709175-c4c0fb50-a6c6-4498-b988-dd7e33f8065a.png)
