### ISSUE TITLE
Android Basics Test Navigation Components content missing

### ISSUE THREAD

**Issue by GPRSBirkbeck** [google-developer-training/android-basics-kotlin-words-app#229]
**URL of codelab**
developer.android.com/codelabs/android-basics-kotlin-test-navigation-components?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-3-pathway-2%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fandroid-basics-kotlin-test-navigation-components#5

**In which task and step of the codelab can this issue be found?**
At the end of step 6

**Describe the problem**
Step 6 ends in the following statement:
"Your test should look something like this:"
But there is no image following this sentence.

**Steps to reproduce?**
1. Go to... step 6
2. Click on... N/A
3. See error... N/A 

**Versions**
_Android Studio version:_  N/A
_API version of the emulator:_  N/A

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._
N/A

**Comment by osuleymanova** [comment]
@GPRSBirkbeck 
Thank you for reaching out to us. The issue is fixed and will be published soon:


![Screen Shot 2022-06-14 at 4 06 31 PM](https://user-images.githubusercontent.com/86437155/173704254-9daecdaf-094d-45b0-a605-5dc67aae1ccd.png)
