### ISSUE TITLE
Android Basics: Activities and intents

### ISSUE THREAD

**Issue by Titanium933** [google-developer-training/android-basics-kotlin-words-app#23]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-activities-intents?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-3-pathway-1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-activities-intents#5

**In which task and step of the codelab can this issue be found?**
Step 6(Se tup DetailActivity) paragraph 5

**Describe the problem**
This is paragraph 5:
While you're at it, you can also move any other hard coded value into the companion object in DetailActivity. **Remember when you performed the implicit intent in the WordAdapter**, you passed in part of the URL to perform a Google search? Go ahead and move this to the companion object as a new constant called SEARCH_PREFIX. The companion object should now contain two constants.

The problem is that the step described as already done, is on the next step "7 Set up Implicit Intent. So it is confusing for somebody trying to remember and go searching backwards for something that it was never there, and finaly when gives up searching recalling his memory and moves to the next step, finding out that paragraph 5 refers to a next step. It is no big deal but I'm trying to help others from wasting time.

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by jtavva** [comment]
@Titanium933 
Thank you so much for reporting this issue. This is fixed and will be published soon.
