### ISSUE TITLE
Android Basics: Activities and intents - here we go again - more errors

### ISSUE THREAD

**Issue by programify** [google-developer-training/android-basics-kotlin-words-app#230]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-activities-intents?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-3-pathway-1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-activities-intents#2

**In which task and step of the codelab can this issue be found?**
3 Overview

**Describe the problem**
There is no "DetailActivity", instead there's "LetterListFragment" and "WordListFragment" neither are shown in the screen image.

**Comment by viperguynaz** [comment]
make sure you checkout the `starter` branch
