### ISSUE TITLE
Android Basics: Activities and intents

### ISSUE THREAD

**Issue by programify** [google-developer-training/android-basics-kotlin-words-app#232]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-activities-intents?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-3-pathway-1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-activities-intents#4

**In which task and step of the codelab can this issue be found?**
5. Set Up Explicit Intent

**Describe the problem**
The course material relates to a previous version of the software downloaded from GitHub.

Again we have to guess what might work. Here we thought LetterListFragment( ) might be the new name for the missing DetailActivity thing.

```
override fun onBindViewHolder (holder : LetterViewHolder, position : Int)
    {
        val item = list.get (position)
        holder.button.text = item.toString ()
    // Assigns a [OnClickListener] to the button contained in the [ViewHolder]
        holder.button.setOnClickListener {
            val context = holder.view.context
            val intent = Intent (context, LetterListFragment::class.java)
            intent.putExtra ("letter", holder.button.text.toString ())
            context.startActivity (intent)

        // Create an action from WordList to DetailList
        // using the required arguments
            val action = LetterListFragmentDirections
                            .actionLetterListFragmentToWordListFragment (letter = holder.button.text.toString ())
        // Navigate using that action
            holder.view.findNavController ().navigate(action) }
    }
```

So the app will just stop working when you press a button. Hardly surprising - we know it's wrong but the course has not given us the tools to figure out what.

I strongly recommend anyone following this course to consider abandoning it and find a more reliable source of instruction. Can the authors recommend another verified source instead of attempting to fix ALL the countless errors in this course so far and ALL those that await?

**Comment by viperguynaz** [comment]
make sure you checkout the `starter` branch
