### ISSUE TITLE
Android Basics: Activities and intents

### ISSUE THREAD

**Issue by diskostu** [google-developer-training/android-basics-kotlin-words-app#233]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-activities-intents

**In which task and step of the codelab can this issue be found?**
Set Up Explicit Intent

**Describe the problem**
The code says:
```kotlin
intent.putExtra("letter", holder.button.text.toString())
```
And the docs say, it is necessary to call `toString()` at the end, because the `putExtra()`-method only accepts `String`s as the second argument.
I think that's not correct; the `putExtra()`-method also accepts a `CharSequence` as the second argument.
![image](https://user-images.githubusercontent.com/574147/149555740-f9ad5d1d-0295-4844-b0f9-ada40b91ebbf.png)

I tried this code, it works.

**Comment by AdityaBavadekar** [comment]
I think that the `DetailActivity` that queries the extras, expects the `letter` to be a string. If you put CharSequence in the extras then you should use `intent?.extras?.getCharSequence("letter")`
