### ISSUE TITLE
Cannot Access class 'kotlin.ranges.CharRange'

### ISSUE THREAD

**Issue by rakuzi** [google-developer-training/android-basics-kotlin-words-app#235]
Downloaded the project. Run it as it. There is problem in LetterAdapter.kt. 

`Cannot access class 'kotlin.ranges.CharRange'. Check your module classpath for missing or conflicting dependencies`

Also `toList()` is also red.

![rangeToError](https://user-images.githubusercontent.com/5767223/149792671-fe45cc4c-8816-470f-b2ad-b76486e6153a.png)

**Comment by rakuzi** [comment]
It magically disappears!

**Comment by TecBrat** [comment]
I have worked up to step **7. Set Up Implicit Intent** and the problem appeared.
