### ISSUE TITLE
Android Basics: Activities and intents

### ISSUE THREAD

**Issue by mulv93** [google-developer-training/android-basics-kotlin-words-app#236]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-activities-intents?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-3-pathway-1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-activities-intents#8

**In which task and step of the codelab can this issue be found?**
9 - Last override function

**Describe the problem**
When running the code, Android Studio alerts a mistake on line 86 ("override fun oneOptionsItemSelected") and indicates that nothing is being overridden here. 

When deleting the "override" attribute of the function, the code compiles without any issues. 

**Steps to reproduce?**
(See explanation above)

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by spamshot** [comment]
Hello
looks like you have a type-O should be onOptionsItemSelected not oneOptionsItemSelected

**Comment by mulv93** [comment]
> Hello
> looks like you have a type-O should be onOptionsItemSelected not oneOptionsItemSelected

Thank you!!

**Comment by osuleymanova** [comment]
The typo in the user's code was found. The ticket is closed as resolved.
