### ISSUE TITLE
Android Basics: Preference Datastore

### ISSUE THREAD

**Issue by RafaelGCPP** [google-developer-training/android-basics-kotlin-words-app#242]
**URL of codelab**

https://developer.android.com/courses/pathways/android-basics-kotlin-unit-5-pathway-2?hl=en#codelab-https://developer.android.com/codelabs/basic-android-kotlin-training-preferences-datastore

**In which task and step of the codelab can this issue be found?**

Task 4 , Step 4

**Describe the problem**

The tutorial ask to "Add a constructor parameter to the SettingsDataStore class of the type Context", but then we get the error "<html>Property delegate must have a 'getValue(Context, KProperty&lt;*&gt;)' method. None of the following functions is suitable:<br/>public abstract operator fun getValue(thisRef: Context, property: KProperty&lt;*&gt;): DataStore&lt;Preferences&gt; defined in kotlin.properties.ReadOnlyProperty" and a bunch of type mismatch errors.

**Steps to reproduce?**
1. Implement the application as stated in https://developer.android.com/courses/pathways/android-basics-kotlin-unit-5-pathway-2?hl=en#codelab-https://developer.android.com/codelabs/basic-android-kotlin-training-preferences-datastore
2. Add a constructor parameter to the SettingsDataStore class of the type Context
3. Get compiling errors as the constructor is not correctly formed

**Versions**
_Android Studio version:_  2021.1.1
_API version of the emulator:_ 30

**Comment by Gui88** [comment]
Had the same problem, added kotlinx-coroutine-android dependency and it worked:

```
dependencies {
    (...)
    implementation "androidx.datastore:datastore-preferences:1.0.0"
    implementation "androidx.lifecycle:lifecycle-livedata-ktx:2.3.1"
    implementation "org.jetbrains.kotlinx:kotlinx-coroutines-android:1.5.2"
}
```

**Comment by ampeixoto** [comment]
Got this issue because I was importing the wrong Preferences class.

Replace this:
```
import java.util.prefs.Preferences
```
By:
```
import androidx.datastore.preferences.core.Preferences
```
