### ISSUE TITLE
java.lang.AbstractMethodError: abstract method androidx.navigation.NavDestination

### ISSUE THREAD

**Issue by ali-koohi** [google-developer-training/android-basics-kotlin-words-app#247]
**URL of codelab**

https://developer.android.com/codelabs/android-basics-kotlin-test-navigation-components?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-3-pathway-2%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fandroid-basics-kotlin-test-navigation-components#5

**In which task and step of the codelab can this issue be found?**

Test Navigation Components step 6

**Describe the problem**

i get below error when use : androidx.navigation:navigation-testing:2.4.0 but its ok on androidx.navigation:navigation-testing:2.3.5

error:
java.lang.AbstractMethodError: abstract method "androidx.navigation.NavDestination androidx.navigation.Navigator.navigate(androidx.navigation.NavDestination, android.os.Bundle, androidx.navigation.NavOptions, androidx.navigation.Navigator$Extras)

**Versions**
_Android Studio version:  Android Studio Bumblebee | 2021.1.1

_API version of the emulator: 30

**Comment by ShahsTestingZone** [comment]
I am also having the same problem! The only solutions seems to be downgrading to 2.3.5
