### ISSUE TITLE
Android Basics: Activities and intents

### ISSUE THREAD

**Issue by kchaou-fakhri** [google-developer-training/android-basics-kotlin-words-app#249]
**URL of codelab**

**In which task and step of the codelab can this issue be found?**

step 4
**Describe the problem**
Class DetailActivity not found !!

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by AdityaBavadekar** [comment]
Hi @kchaou-fakhri , please try adding this file https://github.com/google-developer-training/android-basics-kotlin-words-app/blob/starter/app/src/main/java/com/example/wordsapp/DetailActivity.kt
