### ISSUE TITLE
Android Basics: Activities and intents

### ISSUE THREAD

**Issue by brucemch** [google-developer-training/android-basics-kotlin-words-app#25]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-activities-intents?authuser=1&continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-3-pathway-1%3Fauthuser%3D1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-activities-intents#5

**In which task and step of the codelab can this issue be found?**
Activities and Intents CodeLab, Step 6 (Set Up DetailActivity), Cleaning Up section, steps 5 & 6

**Describe the problem**
Cleaning Up section, steps 5 & 6 describe defining the search constant for the Implicit Intent, which has not been set up yet (it is the next step (Step 7) of this CodeLab. Perhaps Cleaning Up steps 5 & 6 should be moved to the following section on setting up the Implicit Intent, or the all the Code Clean Up should be moved to after both the explicit and implicit Intents have been setup. 

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by jtavva** [comment]
@brucemch 
Thank you so much for reporting this issue. This is fixed and will be published soon.
