### ISSUE TITLE
Android Basics: Fragments Navigation component

### ISSUE THREAD

**Issue by jiaqiu-09** [google-developer-training/android-basics-kotlin-words-app#250]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-fragments-navigation-component?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-3-pathway-2%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-fragments-navigation-component#7

**In which task and step of the codelab can this issue be found?**
task: Fragments and the Navigation Component
step: 8. Using the Navigation Graph

**Describe the problem**
translate error in Chinese version
![image](https://user-images.githubusercontent.com/15116421/154179545-85fb9a7e-8539-4d15-a075-942b5b0d9ac7.png)
![image](https://user-images.githubusercontent.com/15116421/154179822-b89a80e4-5916-47fc-ac33-315cf4c43d9b.png)

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by Jiujiale** [comment]
and the attribute called `app:navHost` is not found
