### ISSUE TITLE
Android Basics: Fragments Navigation component

### ISSUE THREAD

**Issue by EleoXDA** [google-developer-training/android-basics-kotlin-words-app#254]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-fragments-navigation-component#6

**In which task and step of the codelab can this issue be found?**
[Fragments and the Navigation Component]-> [7. Jetpack Navigation Component]->[Safe Args Plugin]->[In the app-level build.gradle file, within plugins at the top, add androidx.navigation.safeargs.kotlin.]

**Describe the problem**
Later bug in android studio doesn't allow building app with an error:
[Class 'ActionLetterListFragmentToWordListFragment' is not abstract and does not implement abstract member public abstract val actionId: Int defined in androidx.navigation.NavDirections]
To fix it, when adding plugin line, we should add
`    id 'androidx.navigation.safeargs'`
instead of
`    id 'androidx.navigation.safeargs.kotlin'`

This was described and fixed in StackOverflow [Link: https://stackoverflow.com/questions/68596264/class-action-is-not-abstract-and-does-not-implement-abstract-member-public-abs]

**Steps to reproduce?**
1. Finish [https://developer.android.com/codelabs/basic-android-kotlin-training-fragments-navigation-component#9] and rebuild app
2. Observe error: [Class 'ActionLetterListFragmentToWordListFragment' is not abstract and does not implement abstract member public abstract val actionId: Int defined in androidx.navigation.NavDirections]

**Versions**
_Android Studio version:_ Bumblebee 2021.1.1 Patch 1 (February 1, 2022)
_API version of the emulator:_ API31 (android 12)

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._
![image](https://user-images.githubusercontent.com/27622683/154679222-3d50b074-86fa-47f8-8418-e24e8e96ac12.png)
![image](https://user-images.githubusercontent.com/27622683/154680004-95ce4ac5-0e8e-4f55-94f1-31e29acfcd01.png)

**Comment by osuleymanova** [comment]
@EleoXDA 
Thank you for contacting us and sharing your feedback. It's good to know that, taking into account your AS version and environment settings, you've found the right solution to compile your code.
