### ISSUE TITLE
Abrupt end of page

### ISSUE THREAD

**Issue by EleoXDA** [google-developer-training/android-basics-kotlin-words-app#255]
**URL of codelab**
https://developer.android.com/codelabs/android-basics-kotlin-test-navigation-components#5

**Describe the problem**
Page ends with:
`Your test should look something like this:`
With no further text.

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._
![image](https://user-images.githubusercontent.com/27622683/154714591-762f123c-4fff-4aae-b9fd-d5949db54794.png)

**Comment by wgoodey** [comment]
I found the missing code [here](https://github.com/google-developer-training/android-basics-kotlin-words-app/blob/nav_test_solution/app/src/androidTest/java/com/example/wordsapp/NavigationTests.kt):

However, I was still getting illegalStateException: you cannot access the navigator's state until the navigator is attached. I updated the dependencies they have you add in step 5 and then the test passed for me. 
Change 
`androidTestImplementation 'androidx.navigation:navigation-testing:2.3.5'`
to 
`androidTestImplementation 'androidx.navigation:navigation-testing:2.4.2'`

**Comment by osuleymanova** [comment]
@EleoXDA 
Thank you for reaching out to us. The code snippet is added and will be published soon:
![Screen Shot 2022-06-14 at 4 06 31 PM](https://user-images.githubusercontent.com/86437155/173703741-8f81fabd-83fa-479c-8c0d-8ceda137f67b.png)
