### ISSUE TITLE
Android Basics: Activities and intents

### ISSUE THREAD

**Issue by Yeongjo-Jeong** [google-developer-training/android-basics-kotlin-words-app#256]
**URL of codelab**

**In which task and step of the codelab can this issue be found?**
 Where to do 3rd work? context.startActivity(intent) ???

**Describe the problem**

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by osuleymanova** [comment]
@Yeongjo-Jeong 
Please provide the requested information to proceed further. Unfortunately the issue will be closed within 7 days if there is no further update.

**Comment by osuleymanova** [comment]
Closing this issue, since there is no issue description.
Please create a new one, if you need help.
All the best learning Android.
