### ISSUE TITLE
Android Basics: Activities and intents

### ISSUE THREAD

**Issue by GregBradb** [google-developer-training/android-basics-kotlin-words-app#26]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-activities-intents?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-3-pathway-1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-activities-intents#5

**In which task and step of the codelab can this issue be found?**
Task 6, Step 6

**Describe the problem**
Step 6 reads as follows:
    You can now replace the hardcoded URL with the SEARCH_PREFIX constant. Edit the queryUrl in the onClickListener in 
    WordAdapter as follows.

    val queryUrl: Uri = Uri.parse("${DetailActivity.SEARCH_PREFIX}${item}")

But there is no onClickListener in the WordAdapt.kt file.  There is no "queryUrl" variable anywhere in all the files in the existing code.

**Steps to reproduce?**
1. Go to...          Download the code from Github
2. Click on...      Do a global search for "queryUrl" or "https"
3. See error...    Not found

**Versions**
_Android Studio version:_           4.1.1
_API version of the emulator:_     29

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

![image](https://user-images.githubusercontent.com/8106705/103805598-a863b800-5008-11eb-8f49-a6ef0f353850.png)

**Comment by jtavva** [comment]
@GregBradb 
Thank you so much for reporting this issue. This is fixed and will be published soon.
