### ISSUE TITLE
Android Basics: Fragments Navigation component/ setHasOptions shows red

### ISSUE THREAD

**Issue by jh115424** [google-developer-training/android-basics-kotlin-words-app#267]
**URL of codelab**

**In which task and step of the codelab can this issue be found?**

**Describe the problem**

setHasOptions shows as red and says has "unresolved Reference, even though the tutorial says put it.   Can't go on until this is fixed.

PLEASE ANSWER PROMPTLY.

<img width="1440" alt="Screen Shot 2022-03-30 at 7 28 22 AM" src="https://user-images.githubusercontent.com/91148652/160834415-4a65914a-1672-4cb5-88f5-2bd425c8f91e.png">

<img width="1440" alt="Screen Shot 2022-03-30 at 7 29 59 AM" src="https://user-images.githubusercontent.com/91148652/160834738-61fec608-43df-4b81-aa88-661c176070c4.png">

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by Gui88** [comment]
The tutorial says `setHasOptionsMenu` not `setHasOptions`.

**Comment by jh115424** [comment]
omg.....sorry

thanks


Jennifer Hodge

Internet Sales

414-586-5425

Russ Darrow Honda


[cid:6af99135-e641-48ba-a9f5-eadcd235de2a]<https://your.tradeinvalet.com/tdhe0j>

________________________________

**Comment by osuleymanova** [comment]
@jh115424 
Thank you for reaching out to us. The ticket is closed as there is no error in the code provided in the codelab.
