### ISSUE TITLE
Android Basics: Fragments Navigation component

### ISSUE THREAD

**Issue by jh115424** [google-developer-training/android-basics-kotlin-words-app#268]
**URL of codelab**
**https://developer.android.com/codelabs/basic-android-kotlin-training-fragments-navigation-component#4**

**In which task and step of the codelab can this issue be found?**

**Describe the problem**

**in private fun chooseLayout, "this" is underlined in red when it asked me in step 5 to move it over from Main Activity to LetterListFragment.

Screen shots below.    Do I have it in the correct spot?  I moved it to different places but it still is red.**

<img width="1440" alt="Screen Shot 2022-04-02 at 7 20 45 AM" src="https://user-images.githubusercontent.com/91148652/161383084-c444e766-07bc-4c5b-a2aa-418d7517f002.png">

<img width="1440" alt="Screen Shot 2022-04-02 at 7 21 07 AM" src="https://user-images.githubusercontent.com/91148652/161383087-eb6f3505-e226-445b-8161-ce1426181646.png">

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by spamshot** [comment]
In a fragment you use context not this.
on 5. Implement Letter List Fragment, section 8. Fragment does not have this property
https://developer.android.com/codelabs/basic-android-kotlin-training-fragments-navigation-component?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-3-pathway-2%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-fragments-navigation-component#4

**Comment by jh115424** [comment]
ok, thanks!


Jennifer Hodge

Internet Sales

414-586-5425

Russ Darrow Honda


[cid:b0a9af5e-9506-451c-a787-59c9ece25b26]<https://your.tradeinvalet.com/tdhe0j>

________________________________

**Comment by jh115424** [comment]
oh, I sent a mistake for Unscrambler app.  I sent it 10 minutes ago in Github.

thanks


Jennifer Hodge

Internet Sales

414-586-5425

Russ Darrow Honda


[cid:02d26709-870d-43a0-8a90-8f1531038735]<https://your.tradeinvalet.com/tdhe0j>

________________________________

**Comment by osuleymanova** [comment]
@jh115424 
Thank you for contacting us and providing the screenshot with the error.
As it was mentioned in the codelab, you can't pass in **this** (referring to the fragment object) as the layout manager's context:

![Screen Shot 2022-10-03 at 11 26 57 AM](https://user-images.githubusercontent.com/86437155/193654633-48dc074f-d00a-45e4-a619-efaabcb6dac1.png)
Please follow the steps provided further in the codelab.
