### ISSUE TITLE
Android Basics: Activities and intents/.   CHOOSE LAYOUT GIVES RED ERROR IN LAST STEP

### ISSUE THREAD

**Issue by jh115424** [google-developer-training/android-basics-kotlin-words-app#269]
**URL of codelab**

**In which task and step of the codelab can this issue be found?**

**Describe the problem**

SEE SCREEN SHOTS
<img width="1440" alt="Screen Shot 2022-04-10 at 8 02 49 AM" src="https://user-images.githubusercontent.com/91148652/162619533-062a06df-136a-4b64-b61e-0a268f1cc4eb.png">

<img width="1440" alt="Screen Shot 2022-04-10 at 8 03 49 AM" src="https://user-images.githubusercontent.com/91148652/162619561-cc77f136-4b8b-4947-a856-936a1e4bf299.png">

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by AdityaBavadekar** [comment]
Hi @jh115424, it seems that you haven't added the
 `chooseLayout()` function in your file.
Please add this : 
```kt
/**
     * Sets the LayoutManager for the [RecyclerView] based on the desired orientation of the list.
     *
     * Notice that because the enclosing class has changed from an Activity to a Fragment,
     * the signature of the LayoutManagers has to slightly change.
     */
    private fun chooseLayout() {
        if (isLinearLayoutManager) {
            recyclerView.layoutManager = LinearLayoutManager(context)
        } else {
            recyclerView.layoutManager = GridLayoutManager(context, 4)
        }
        recyclerView.adapter = LetterAdapter()
    }
```

**Comment by jh115424** [comment]
thanks!

Can you please look at the issue I sent for the Lemonade app?

Me and other people have the same problem.    The code no longer works.     I sent in a screen shot.   Please look!

thanks


Jennifer Hodge

Internet Sales

414-586-5425

Russ Darrow Honda


[cid:d89c7ede-9acf-4098-8140-9c8f8a6be46b]<https://your.tradeinvalet.com/tdhe0j>

________________________________
