### ISSUE TITLE
Android Basics: Activities and intents

### ISSUE THREAD

**Issue by ubertrombone** [google-developer-training/android-basics-kotlin-words-app#27]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-activities-intents?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-3-pathway-1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-activities-intents#5

**In which task and step of the codelab can this issue be found?**
Task: Set Up DetailActivity; Step 5

**Describe the problem**
Step 5 covers code that will likely not be explained until the next task of the codelab.
This is just a problem in the lecture material, not the code.

**Comment by jtavva** [comment]
@ubertrombone 
Thank you so much for reporting this issue. This is fixed and will be published soon.
