### ISSUE TITLE
A deprecated method is using 

### ISSUE THREAD

**Issue by Pr0pHesyer** [google-developer-training/android-basics-kotlin-words-app#272]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-fragments-navigation-component?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-3-pathway-2%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-fragments-navigation-component#4

**In which task and step of the codelab can this issue be found?**
The 4th, "fragment 和 Navigation 组件" in Chinese. 

**Describe the problem**
Use `setHasOptionsMenu() ` which is deprecated in the function `onCreate()`.

**Comment by osuleymanova** [comment]
@Pr0pHesyer 
Thank you for contacting us and sharing your feedback.
 As for the release notes: "the method <setHasOptionsMenu()> is no longer needed when using a MenuProvider to provide a Menu to your activity, which replaces onCreateOptionsMenu..." But in our code, this deprecated method doesn't break anything so no need replace it.
