### ISSUE TITLE
Android Basics: Collections

### ISSUE THREAD

**Issue by Lunarclipper** [google-developer-training/android-basics-kotlin-words-app#279]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-collections?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-3-pathway-1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-collections#3

**In which task and step of the codelab can this issue be found?**
Task 4
The highlighted text in the screenshot references the code window below it. Either the text needs to be changed to say ". . .code from below. . ."  or it needs to be moved below the code window so there is actually ". . .code. . .above. . ."
**Describe the problem**

![above_below](https://user-images.githubusercontent.com/94221018/168474994-c9439798-718d-4b5a-9957-ecf53bfecc33.png)

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by osuleymanova** [comment]
@Lunarclipper 
Thank you for reaching out to us. The typo is fixed and will be published soon:

![Screen Shot 2022-09-26 at 2 45 35 PM](https://user-images.githubusercontent.com/86437155/192386492-387ca539-9c3d-4b7e-8fa3-b2b727fb87e9.png)
