### ISSUE TITLE
Android Basics: Fragments Navigation component

### ISSUE THREAD

**Issue by cdev75** [google-developer-training/android-basics-kotlin-words-app#281]
setContentView(binding.root)

I am using Android Studio when I type this code. I see "Unresolved reference: setContentView" and create function "setContentView" 

**In which task and step of the codelab can this issue be found?**

**Describe the problem**

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by osuleymanova** [comment]
@cdev75 
Please provide the required details (codelab URL, step, screenshot, etc.) while reporting an issue so that we can help you with troubleshooting.

**Comment by osuleymanova** [comment]
Closing this issue, since there is no issue description.
Please create a new one, if you need help.
All the best learning Android.
