### ISSUE TITLE
Android Basics: Activities and intents

### ISSUE THREAD

**Issue by alphaunited** [google-developer-training/android-basics-kotlin-words-app#289]
**URL of codelab**

https://developer.android.com/codelabs/basic-android-kotlin-training-activities-intents?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-3-pathway-1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-activities-intents#2

**Describe the problem**

The course content has a different starter code than the actual downloaded code:
course refer to "DetailActivity", but the code does not have this class, thus the code in 5. Set up Explicit Intent and after do not work:
       val context = holder.view.context
        val intent = Intent(context, **DetailActivity**::class.java)
        intent.putExtra("letter", holder.button.text.toString())
        context.startActivity(intent)

**Steps to reproduce?**
1. Go to...download the starter code from the link in 2. Starter code:
https://github.com/google-developer-training/android-basics-kotlin-words-app/tree/starter
2. Click on...Android-> app-> java->
3. See error...

**Versions**
_Android Studio version:_ Bumblebee
_API version of the emulator:_ API 29

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by Dorifor** [comment]
I assume you imported the project in Android Studio with `File->New->Project from Version Control` ?

By importing the project with this, by default it's on the main branch, so you have to explicitly checkout on the 'starter' branch after.

There's a "Git" panel you can expand on the bottom left, in there you have different branches : 
![image](https://user-images.githubusercontent.com/28139590/176865434-c3d25d78-42da-4f72-b695-c241210b5a7b.png)

You then checkout on this branch by right clicking and choosing "checkout" : 
![image](https://user-images.githubusercontent.com/28139590/176865548-b03720be-78dd-43dc-880b-c620b13538fb.png)

Or, you can just open the terminal and write `git checkout starter`.

If you just downloaded the ZIP from the link you provided, then there should've been no problem.

**Comment by osuleymanova** [comment]
@alphaunited 
Thank you for reaching out to us. Please follow the steps how to download the starter code provided in the codelab, you may also refer to the comment shared by @Dorifor.
