### ISSUE TITLE
Android Basics: Activities and intents

### ISSUE THREAD

**Issue by amaljoe** [google-developer-training/android-basics-kotlin-words-app#29]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-activities-intents?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-3-pathway-1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-activities-intents#5

**In which task and step of the codelab can this issue be found?**
Task: Activities and Intents
Step: 6) Setup Detail Activity

**Describe the problem**
"Remember when you performed the implicit intent in the WordAdapter, you passed in part of the URL to perform a Google search?"

The above lines are from step 6 of activities and intents lesson. We learn about implicit intent in step 7 and has not yet set up an implicit intent as mentioned in the above lines.

**Additional information**
![image](https://user-images.githubusercontent.com/16449652/103886267-42118f00-5107-11eb-85df-9e52a38d881b.png)

**Comment by jtavva** [comment]
@amaljoe 
Thank you so much for reporting this issue. This is fixed and will be published soon.
