### ISSUE TITLE
Grandle proyect sync failed. Intents Codelab

### ISSUE THREAD

**Issue by FraTel25** [google-developer-training/android-basics-kotlin-words-app#295]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-activities-intents?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-3-pathway-1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-activities-intents#1

**In which task and step of the codelab can this issue be found?**
Initialize Proyect

**Describe the problem**
when starting, this error appears

Unable to load class 'org.gradle.initialization.BuildCancellationToken'.

This is an unexpected error. Please file a bug containing the idea.log file.

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._
![imagen_2022-07-05_132930014](https://user-images.githubusercontent.com/108759181/177392430-f1498bb7-4623-4488-bd48-ea762e8af1a6.png)

**Comment by osuleymanova** [comment]
@FraTel25 
Thank you for reaching out to us. Please refer to this URL: 
https://stackoverflow.com/questions/49743528/how-to-solve-unable-to-load-class-org-gradle-initialization-buildcancellationt
