### ISSUE TITLE
Android Basics: Activities and intents

### ISSUE THREAD

**Issue by inhaledesign** [google-developer-training/android-basics-kotlin-words-app#298]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-activities-intents

**In which task and step of the codelab can this issue be found?**
9. Implement Menu Button, "Implement as shown onOptionsItemSelected with just a few more lines of code."
**Describe the problem**
There's a syntactical mistake if you're trying to teach `when` as an expression:

```
       R.id.action_switch_layout -> {
           // Sets isLinearLayoutManager (a Boolean) to the opposite value
           isLinearLayoutManager = !isLinearLayoutManager
           // Sets layout and icon
           chooseLayout()
           setIcon(item)

           return true
       }
```

The `return true` here, while effective, is breaking from the when expression. Changing this line to `true` would be more correct, and more educational.

Or maybe I'm being pedantic.

**Comment by osuleymanova** [comment]
@inhaledesign 
Thank you for contacting us and sharing your feedback.
