### ISSUE TITLE
Android Basics: Activities and intents - strange ordering - reference to code from next task

### ISSUE THREAD

**Issue by RichardBenes** [google-developer-training/android-basics-kotlin-words-app#30]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-activities-intents?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-3-pathway-1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-activities-intents#5

**In which task and step of the codelab can this issue be found?**
Task "6. Set Up DetailActivity", step "Cleaning Up", item 5

**Describe the problem**
Text in the item asks the user whether he remembers code from next task (task 7):
"Remember when you performed the implicit intent in the WordAdapter...?"

Not a big deal, but it would be nice to have these things in the right order.

**Comment by jtavva** [comment]
@RichardBenes 
Thank you so much for reporting this issue. This is fixed and will be published soon.
