### ISSUE TITLE
Android Basics: Fragments Navigation component

### ISSUE THREAD

**Issue by Guillermo-Garcia-Perez** [google-developer-training/android-basics-kotlin-words-app#302]
[**URL of codelab**
](https://developer.android.com/codelabs/basic-android-kotlin-training-fragments-navigation-component?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-3-pathway-2%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-fragments-navigation-component#3)

**In which task and step of the codelab can this issue be found?**
Step 4, task 3

**Describe the problem**
On the image referring to "fragment_letter_list.xml" you can read "tools:context=".WordListFragment" when, according to the text, it should be "tools:context=".LetterListFragment"

**Steps to reproduce?** (Nothing else to say here, the problem is in the webpage of the codelab itself)
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._
![image](https://user-images.githubusercontent.com/100037968/179553629-7951c2f0-6fbb-4019-ad18-6c458d44eb31.png)

**Comment by osuleymanova** [comment]
@Guillermo-Garcia-Perez 
Thank you for reaching out to us. Please refer to the correct code in the screenshot below:

![Screen Shot 2022-09-30 at 5 08 23 PM](https://user-images.githubusercontent.com/86437155/193373580-b08b2c78-29da-4c6d-9440-c84171ee8a7c.png)
