### ISSUE TITLE
unable to build the project from starter code

### ISSUE THREAD

**Issue by sluschman** [google-developer-training/android-basics-kotlin-words-app#305]
**URL of codelab**

**In which task and step of the codelab can this issue be found?**
Opening the starter code in Android Studio.

**Describe the problem**
When I try to open the starter code I've downloaded Android Studio suggests I migrate to Android Studio. Apparently something's going wrong with the Gradle. I am new to the subject and get totally confused about this migrating thing, it's too complicated, I don't understand where I am suggested to migrate from, there are several options. What am I doing wrong? Should I upgrade my version of the Studio? 

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ bumblebee
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by Momo-009** [comment]
Have the same problem

**Comment by PedroE36** [comment]
I have the same problem.
Doesn´t work as previous Codelabs.
Import Project leads to the menu: Create project from existing sources / Import project from external model.
Despite several trials and android studio / SDK updates, it doesn´t work.
Need to migrate to Gradle? How?

**Comment by PedroE36** [comment]
I went throughout all the Kotlin files and realize that there are no differences between Activities and Intents codelab (after completion) and this one, although, some additional comments and a couple of question marks (safe calls) were added.
In conclusion, you can easily start this codelab using the solution code from the previous Unit (after completion).

**Comment by m00tiny** [comment]
**In project structure set Gradle to which ever you like (latest stable advised) and above that set agp_version to 7.4.2 (it's probably sitting at 7.2.2). **You will need to click the sliver of a button to the right of the input box to be able to change AGP versions****  
██████████████████  ████████   mootiny@moofasa 
██████████████████  ████████   --------------- 
██████████████████  ████████   OS: Manjaro Linux x86_64 
██████████████████  ████████   Host: Alpha 15 A3DD REV:1.0 
████████            ████████   Kernel: 6.1.23-1-MANJARO 
████████  ████████  ████████   Uptime: 16 hours, 9 mins 
████████  ████████  ████████   Packages: 4638 (pacman), 27 (flatpak), 2 (snap) 
████████  ████████  ████████   Shell: zsh 5.9 
████████  ████████  ████████   Resolution: 1920x1080 
████████  ████████  ████████   DE: Plasma 5.27.4 
████████  ████████  ████████   WM: KWin 
████████  ████████  ████████   Theme: [Plasma], Breeze-Dark [GTK2/3] 
████████  ████████  ████████   Icons: [Plasma], Breeze-Cheerful-Phantasy-Dark [GTK2/3] 
████████  ████████  ████████   Terminal: konsole 
                               Terminal Font: Meslo LG M 12 
                               CPU: AMD Ryzen 7 3750H with Radeon Vega Mobile Gfx (8) @ 2.300GHz 
                               GPU: AMD ATI Radeon RX 5500/5500M / Pro 5500M 
                               GPU: AMD ATI Radeon Vega Series / Radeon Vega Mobile Series 
                               Memory: 16050MiB / 62204MiB 


eeh... currently running android studio latest canary, linuxarch-java is set to java-11-openjdk (think studio doesn't work below 11), Gradle is set to 8.1
