### ISSUE TITLE
Android Basics: Collections

### ISSUE THREAD

**Issue by cesarchavez** [google-developer-training/android-basics-kotlin-words-app#309]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-collections?authuser=1&continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-3-pathway-1%3Fauthuser%3D1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-collections#1

**In which task and step of the codelab can this issue be found?**
On the step 7 

**Describe the problem**
Maybe a minor change is needed? On this part : 

> You can try testing it with a value that is in the set, too.
> 
> 
>     All of the code above:

The part that says "All of the code above:" appears to be a code type of text, but it really doesn't seem to be a code line.

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

![image](https://user-images.githubusercontent.com/1002729/189085784-15f61f21-0b90-4670-808b-8bbd517c7bb3.png)

**Comment by osuleymanova** [comment]
@cesarchavez 
Thank you for reaching out to us. The font is fixed and will be published soon:

![Screen Shot 2022-09-26 at 2 48 00 PM](https://user-images.githubusercontent.com/86437155/192386890-b25c90fd-4766-483f-82f6-37bb06472a97.png)
