### ISSUE TITLE
Error When Running "navigate_to_words_nav_component()" Test [Solution]

### ISSUE THREAD

**Issue by danielcoderman** [google-developer-training/android-basics-kotlin-words-app#310]
**URL of codelab**
https://developer.android.com/codelabs/android-basics-kotlin-test-navigation-components?authuser=3&continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-3-pathway-2%3Fauthuser%3D3%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fandroid-basics-kotlin-test-navigation-components#5

**In which task and step of the codelab can this issue be found?**
6. Write the Navigation Component Test

**Describe the problem**
When running the test function navigate_to_words_nav_component(), a java.lang.AbstractMethodError occurs. The error in more detail looks like the following: java.lang.AbstractMethodError: abstract method "androidx.navigation.NavDestination androidx.navigation.Navigator.navigate(androidx.navigation.NavDestination, android.os.Bundle, androidx.navigation.NavOptions, androidx.navigation.Navigator$Extras)"

**Steps to reproduce? [Solution]**
1. Use differing versions for navigation related dependencies in build.gradle files
What do I mean? For example, in the codelab, we were told to add the following dependency 'androidx.navigation:navigation-testing:2.4.2' in the app's build.gradle file. This navigation related dependency has a version of 2.4.2. This version differs from the version of all the other navigation related dependencies in the gradle files. All the other navigation related dependencies use a variable called nav_version which is set to version 2.3.1 (in my case). This nav_version variable can be found under buildscript > ext in the project's build.gradle file. As soon as I changed the nav_version variable's value to 2.4.2 and synced the build.gradle file, the test function navigate_to_words_nav_component() was able to run without out any errors and passed. After this change, you can optionally replace "androidx.navigation:navigation-testing:2.4.2" with "androidx.navigation:navigation-testing:$nav_version."

**Versions**
_Android Studio version:_ Android Studio Chipmunk | 2021.2.1 Patch 2
_API version of the emulator:_ 31

**Additional information**
Here are two screenshots showing how my build.gradle files look like after everything is working.
<img width="396" alt="build gradle (app)" src="https://user-images.githubusercontent.com/90026471/189251107-2e70929c-1af1-48c5-bea3-5bc6b0049c7e.png">
<img width="387" alt="build gradle (project)" src="https://user-images.githubusercontent.com/90026471/189251115-0eb7c812-27bf-4ebd-9261-d6cc2e3980f0.png">

**Comment by gabof92** [comment]
Very helpful, thank you

**Comment by osuleymanova** [comment]
@danielcoderman 
Thank you for contacting us and sharing your feedback. The repository has been recently updated so no more errors should be observed.
