### ISSUE TITLE
Android Basics: Activities and intents

### ISSUE THREAD

**Issue by Engineers-Lab** [google-developer-training/android-basics-kotlin-words-app#311]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-activities-intents?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-3-pathway-1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-activities-intents#7

**In which task and step of the codelab can this issue be found?**
2nd paragraph: 
... the app bar can be customized and host lots of useful "_functionality_" ,.....

**Describe the problem**

"functionality" , should be plural, because there is more than one functionality
correction : functionalities 

Thank you.

**Comment by osuleymanova** [comment]
@Engineers-Lab 
Thank you for reaching out to us. Functionality as the range of operations that can be run on a computer or other electronic system is most commonly (and properly) used as a mass noun, so it's not a typo in the codelab.
