### ISSUE TITLE
no .gitignore in android-basics-kotlin-words-app-activities

### ISSUE THREAD

**Issue by KateChubarova** [google-developer-training/android-basics-kotlin-words-app#32]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-fragments-navigation-component?authuser=1&continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-3-pathway-2%3Fauthuser%3D1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-fragments-navigation-component#0

**In which task and step of the codelab can this issue be found?**
android-basics-kotlin-words-app-activities

**Describe the problem**
there is no .gitignore in android-basics-kotlin-words-app-activities

**Steps to reproduce?**
1. Go to https://github.com/google-developer-training/android-basics-kotlin-words-app/tree/activities
2. Download the project 
2. Choose /activities branch 
3. Project has just one .gitignore in /app(but it is not include all ignores that are needed) and no common .gitigonre.

**Comment by jtavva** [comment]
@KateChubarova 
Thank you so much for reporting this issue. This is fixed and will be published soon..
