### ISSUE TITLE
Android Basics: Activities and intents

### ISSUE THREAD

**Issue by NayanPahuja** [google-developer-training/android-basics-kotlin-words-app#321]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-activities-intents?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-3-pathway-1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-activities-intents#2

**In which task and step of the codelab can this issue be found?**
Whole Codelab

**Describe the problem**
The gradle and android studio in the starter project is actually a lot older and hence it is unable to sync and run with the current android studio. It faces ssl peer shutdown incorrectly and many more errors related to plugins and gradle.
**Steps to reproduce?**
1. Go to android studio
2. Click on run app/ sync files
3. See error

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by schordas** [comment]
The versions and dependencies have been updated in the codelabs and branches.
