### ISSUE TITLE
Android Basics: Fragments Navigation component

### ISSUE THREAD

**Issue by AtanFili** [google-developer-training/android-basics-kotlin-words-app#323]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-fragments-navigation-component?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-3-pathway-2%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-fragments-navigation-component#6

**In which task and step of the codelab can this issue be found?**

Dependencies and plugins are not working :)
**Describe the problem**

Build file 'C:\Users\Filip\Downloads\android-basics-kotlin-words-app-activities (1)\android-basics-kotlin-words-app-activities\build.gradle' line: 36

Could not compile build file 'C:\Users\Filip\Downloads\android-basics-kotlin-words-app-activities (1)\android-basics-kotlin-words-app-activities\build.gradle'.
> startup failed:
  build file 'C:\Users\Filip\Downloads\android-basics-kotlin-words-app-activities (1)\android-basics-kotlin-words-app-activities\build.gradle': 36: unable to resolve class val 
   @ line 36, column 21.
                     val nav_version = "2.5.2"

This is in the Build
                         ^

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by osuleymanova** [comment]
@AtanFili 
Thank you for reaching out to us. 
If in line 36 you replace val nav_version = "2.5.2" with nav_version = "2.5.2", the build  compiles without errors.
