### ISSUE TITLE
Android Basics: Fragments Navigation component

### ISSUE THREAD

**Issue by GregBradb** [google-developer-training/android-basics-kotlin-words-app#33]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-fragments-navigation-component?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-3-pathway-2%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-fragments-navigation-component#3

**In which task and step of the codelab can this issue be found?**
4. Create Fragment and layout Files

**Describe the problem**
The description has, for the final content of fragment_letter_list.xml

   tools:context=".WordListFragment">

But the text for this entry says to make it:

   tools:context=".LetterListFragment">

**Steps to reproduce?**
1. Go to...  the link above, at the bottom of the page
2. Click on...  N/A
3. See error...  in the text describing the content of the fragment_leter_list.xml file

**Versions**
_Android Studio version:_   4.1.1
_API version of the emulator:_   29

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._
![image](https://user-images.githubusercontent.com/8106705/104126878-e9631180-5313-11eb-9ca0-7b7c72b629a5.png)

**Comment by jtavva** [comment]
@GregBradb 
Thank you so much for reporting this issue. This is fixed and will be published soon.

**Comment by jtavva** [comment]
PR: https://github.com/google-developer-training/android-basics-kotlin-words-app/pull/44
