### ISSUE TITLE
Android Basics: Activities and intents

### ISSUE THREAD

**Issue by hell-storm2004** [google-developer-training/android-basics-kotlin-words-app#339]
[**URL of codelab**](https://developer.android.com/codelabs/basic-android-kotlin-training-activities-intents?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-3-pathway-1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-activities-intents#4)

[5. Set Up Explicit Intent](https://developer.android.com/codelabs/basic-android-kotlin-training-activities-intents?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-3-pathway-1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-activities-intents#4)

Somehow the tutorial talks about a class called DetailActivity. The way it is described, I am assuming it will come from the GitHub URL shared in the previous chapter. But after checkout I don't see the class. I initially thought there would be lessons in building the class from scratch. But I don't think that is the case. I am thinking WordAdapter has replaced DetailActivity. But the tutorial doesn't reflect that. 

Can you please clarify.

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by StephanVanBiljon** [comment]
Make sure that you're getting the code from the starter branch, not the main branch.
