### ISSUE TITLE
Android Basics: Activities and intents

### ISSUE THREAD

**Issue by carlolf** [google-developer-training/android-basics-kotlin-words-app#34]
In step 6 the explanations are only understandable if you already read step 7. When I read "Remember when you performed the implicit intent in the WordAdapter, you passed in part of the URL to perform a Google search?" I did not understand what is going on.

**Comment by jtavva** [comment]
@carlolf 
We appreciate you bringing this issue to our attention.
We updated the instructions this should be fixed now.
