### ISSUE TITLE
Android Basics: Activities and intents

### ISSUE THREAD

**Issue by nicholeb** [google-developer-training/android-basics-kotlin-words-app#35]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-activities-intents#5

**In which task and step of the codelab can this issue be found?**
"cleaning up" (5) in task 6

**Describe the problem**
It says "While you're at it, you can also move any other hard coded value into the companion object in DetailActivity. Remember when you performed the implicit intent in the WordAdapter, you passed in part of the URL to perform a Google search? Go ahead and move this to the companion object as a new constant called SEARCH_PREFIX. The companion object should now contain two constants."

The implicit intent in the WordAdapter is in the next step and hasn't been completed before getting to this step.

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by nicholeb** [comment]
Also in the next step it says "Open up WordAdapter and in the button's onClickListener in onBindViewHolder. Start by creating a URI for the search query." but there isn't an onClickListener.

**Comment by jtavva** [comment]
@nicholeb 
Thank you so much for reporting this issue. This is fixed and will be published soon.
