### ISSUE TITLE
Android Basics: Activities and intents

### ISSUE THREAD

**Issue by darinaTo** [google-developer-training/android-basics-kotlin-words-app#355]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-activities-intents?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-3-pathway-1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-activities-intents#4

**In which task and step of the codelab can this issue be found?**
Step 2
**Describe the problem**
The code I found in the URL course didn't assign instructions in the course. Has another structure and task

**Comment by Yviee** [comment]
I had the same problem - you're probably on the wrong branch after you cloned the project. 
Here's the solution: In Android Studio, on the right lower corner, click on the Git branch symbol, which most likely says "main" next to it. Checkout the starter branch. Hope this helps.
