### ISSUE TITLE
Android Basics: Fragments Navigation component typo

### ISSUE THREAD

**Issue by zprima** [google-developer-training/android-basics-kotlin-words-app#41]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-fragments-navigation-component?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-3-pathway-2%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-fragments-navigation-component#7

**In which task and step of the codelab can this issue be found?**
Step 8

**Describe the problem**
Text says: ".. add an attribute called **app:navHost** and set it equal to .."
It should say: "... add an attribute called **app:defaultNavHost** and set it equal to .." to match with the next code snippet below this text.

**Comment by jtavva** [comment]
@zprima 
Thank you so much for reporting this issue. 
This is fixed and will be published soon..
