### ISSUE TITLE
Android Basics: Implement Fragment Instruction Typo

### ISSUE THREAD

**Issue by Tohure** [google-developer-training/android-basics-kotlin-words-app#43]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-fragments-navigation-component?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-3-pathway-2%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-fragments-navigation-component#4

**In which task and step of the codelab can this issue be found?**
Step 5

**Describe the problem**
The instruction 3 of this _Step 5_ says:

3. To implement **onCreate()**, simply call **setHasOptionsMenu()**.

<img width="476" alt="Screen Shot 2021-01-25 at 23 51 41" src="https://user-images.githubusercontent.com/11746842/105802108-8c4c9a00-5f68-11eb-9420-179d59c9ff30.png">

That doesn't make sense, if I read it literally it says to implement _onCreate_() method "simply" should I call "_setHasOptionsMenu_"?. Here is a typo or write something like: To implement the **AppBar** or menu buttons you must call _setHasOptionsMenu_ in the _onCreate_. 

Otherwise the reading makes it look like "_setHasOptionsMenu function_" is needed to "_implement the onCreate method_".

**Comment by jtavva** [comment]
@Tohure 
Thank you so much for reporting this issue.  We updated the instructions.
This is fixed and will be published soon.

**Comment by Tohure** [comment]
Your welcome
