### ISSUE TITLE
Android Basics: Fragments Navigation component Typo

### ISSUE THREAD

**Issue by 05dbec67c6** [google-developer-training/android-basics-kotlin-words-app#47]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-fragments-navigation-component#0

**In which task and step of the codelab can this issue be found?**
Task 1 "Before you begin"

**Describe the problem**
It's a typo, t in fragment is missing in the third paragraph
"...You can even show multiple fragments at once on a single screen, such as a master-detail layout for tablet devices. In the example below, both the navigation UI on the left and the content on the right can each be contained in a separate !!!!!!!!!!!!!!!!!!!!!fragmen. !!!!!!!!!!!!!!!!!!!Both fragments exist simultaneously in the same activity.

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by jtavva** [comment]
@05dbec67c6 
Thank you so much for reporting this issue. This is fixed and will be published soon.
