### ISSUE TITLE
Android Basics: Fragments Navigation component

### ISSUE THREAD

**Issue by MiGei333** [google-developer-training/android-basics-kotlin-words-app#48]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-fragments-navigation-component?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-3-pathway-2%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-fragments-navigation-component#3

**In which task and step of the codelab can this issue be found?**
Fragments and the Navigation Component, Step 4 Create Fragment and Layout files

**Describe the problem**
In the content for fragment_letter_list.xml at the bottom of the step, tool:context is falsely set to ".WordListFragment" instead of ".LetterListFragment"

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._
![image](https://user-images.githubusercontent.com/67139349/106768266-09989e80-663c-11eb-806e-1ac7048b4157.png)

**Comment by jtavva** [comment]
@MiGei333 
Thank you so much for reporting this issue. This is fixed and will be published soon.
