### ISSUE TITLE
Android Basics: Activities and intents - Missing onClickListener

### ISSUE THREAD

**Issue by Jacob276** [google-developer-training/android-basics-kotlin-words-app#5]
**URL of codelab**

https://developer.android.com/codelabs/basic-android-kotlin-training-activities-intents#5

**In which task and step of the codelab can this issue be found?**

Task 6. - Set Up DetailActivity -> Cleaning up -> step 6

**Describe the problem**
There's no onClickListener in WordAdapter in the starter code. 
This step is in some way repeating the step 1 in task 7. This could cause cofusion. To find the missing peice of code I looked at the solution code (task 10)

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_  4.1.1
_API version of the emulator:_ 27

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

![image](https://user-images.githubusercontent.com/53948109/102701541-a48e1280-4260-11eb-8462-ea567a582849.png)

**Comment by jtavva** [comment]
@Jacob276 
Thank you for reaching out to us.
You will add `holder.button.setOnClickListener { }` callback method in the [Task 5](https://developer.android.com/codelabs/basic-android-kotlin-training-activities-intents#5).
Let us know if that answers your question.

**Comment by jtavva** [comment]
@Jacob276 
Thank you so much for reporting this issue. This is fixed and will be published soon.
