### ISSUE TITLE
Android Basics: Activities and intents

### ISSUE THREAD

**Issue by patfla** [google-developer-training/android-basics-kotlin-words-app#52]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-activities-intents?hl=en&continue=https%3A%2F%2Fcodelabs.developers.google.com%2F%3Fcat%3Dandroid%26authuser%3D2%237#7

**In which task and step of the codelab can this issue be found?**
Step 8

**Describe the problem**
Where do "view module" and "view list" come from?  As an expedient, I copied this code from out of the finished project at github.

Pat

**Comment by danielslabo** [comment]
Which Task's Step 8 are you referring to?
