### ISSUE TITLE
Android Basics: Fragments Navigation component

### ISSUE THREAD

**Issue by nokyslash** [google-developer-training/android-basics-kotlin-words-app#60]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-fragments-navigation-component?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-3-pathway-2%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-fragments-navigation-component#4

**In which task and step of the codelab can this issue be found?**
Task 2
Step 5

**Describe the problem**
The code provided by the codelab for onCreateView (), throws an error in my Android Studio

**Steps to reproduce?**
1. Go to... th URL
2. Click on... Task 2 and later Step 5
3. See error...The code shown for point 4 of the creation of the LetterListFragment, specifically for override onCreateView () throws an error in Android Studio

**Versions**
_Android Studio version:_ 4.1
_API version of the emulator:_ Physical Device

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._
![Sin título](https://user-images.githubusercontent.com/46078334/110000504-5e821000-7ce1-11eb-9b71-01220e4d48df.png)

**Comment by nokyslash** [comment]
oppp!! Sorry my bad, I had misdeclared the type of _binding

**Comment by jtavva** [comment]
@nokyslash 
Thank you for reaching out to us.
Let us know if you need further assistance.
