### ISSUE TITLE
Android Basics: The code is not the same as the developer documentation shows

### ISSUE THREAD

**Issue by Nthily** [google-developer-training/android-basics-kotlin-words-app#61]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-activities-intents?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-3-pathway-1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-activities-intents#2

**In which task and step of the codelab can this issue be found?**
 I found that the code downloaded from the github repository is not the same as the image shown in the documentation

![M1VH6I9F@3UZ0HEH UQ3C$3](https://user-images.githubusercontent.com/31311826/110021929-a75eb680-7d2b-11eb-80e0-13990f4e17da.png)

![D`UWATWWB(8LF I}9SRC@EF](https://user-images.githubusercontent.com/31311826/110021947-acbc0100-7d2b-11eb-943a-36e191543689.png)

When my git clone is done, com.example.wordsapp will look like this

![{X)9X(KMRNRJ`1}V S~E7{E](https://user-images.githubusercontent.com/31311826/110022210-ed1b7f00-7d2b-11eb-94d7-564054c774dd.png)

**Describe the problem**
 I think it might be necessary to update that developer documentation

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by jtavva** [comment]
@Nthily 
Thank you for reaching out to us.
The task [3. Words app overview](https://developer.android.com/codelabs/basic-android-kotlin-training-activities-intents?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-3-pathway-1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-activities-intents#2) refers to the starer code on the starter brach: https://github.com/google-developer-training/android-basics-kotlin-words-app/tree/starter.

I think your code is the final or the solution code from the main or activities branch. Please cross verify and download the correct code.
