### ISSUE TITLE
Android Basics: Activities and intents

### ISSUE THREAD

**Issue by JustSxm** [google-developer-training/android-basics-kotlin-words-app#62]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-activities-intents?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-3-pathway-1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-activities-intents#1

**Describe the problem**
Add a section to explain how to accept licenses.

**Steps to reproduce?**
1. Download Repository
2. Import it to Android Studio
3. Run it

**Versions**
_Android Studio version:_  4.1.2

**Comment by jtavva** [comment]
@JustSxm 
What licenses, could you please provide more explanation? 
Also, add a note to how is this related to this codelab.

**Comment by JustSxm** [comment]
Hello, the actual problem is gradle and such are not updated when you
download the project so you're prompted to update when you open the
project. If you accept to update you must accept licenses in
AndroidStudio/licenses

**Comment by jtavva** [comment]
@JustSxm 
Do you still face this issue?

If yes, could you please provide us with the screenshots, to debug your issue further.  .

**Comment by JustSxm** [comment]
Hello, I apologize for not answering this issue. Updating was not necessary, I've updated but it was not needed. Thank you for the help
