### ISSUE TITLE
Android Basics: Collections

### ISSUE THREAD

**Issue by oschubert** [google-developer-training/android-basics-kotlin-words-app#63]
https://developer.android.com/codelabs/basic-android-kotlin-training-collections

What do collections have to do with "Navigate between screens"???

I understand courses have prerequisites, but these courses are organized very poorly.  If I want to learn about collections, I'll watch a "Collections" tutorial.  If I want to learn about navigation, I watch a "Navigation" tutorial.

**Comment by danielslabo** [comment]
Which Task and Step are you referring to?

**Comment by oschubert** [comment]
It appears that in the March 29 update this comingling of topics was resolved.
