### ISSUE TITLE
Android Basics: Collections

### ISSUE THREAD

**Issue by ShreyasKhandekar** [google-developer-training/android-basics-kotlin-words-app#69]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-collections?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-3-pathway-1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-collections#4

**In which task and step of the codelab can this issue be found?**
Task 5: Make word lists, Step 2.

**Describe the problem**
A code snippet talks about the `startsWith()` function.
It uses markdown formatting for links but since it is displayed as a code snippet the URL is shown in full.
I believe the line was not supposed to be in a code snippet.

**Steps to reproduce?**
1. Go to the URL
2. Click on Task 5
3. See error described in the 2nd code snippet of step 2

![image](https://user-images.githubusercontent.com/60454060/110399490-2bb67f80-8033-11eb-94b5-5d329c8b18ba.png)

**Comment by ShreyasKhandekar** [comment]
Duplicate Issue. My bad
Duplicate of #65 #59 #54 #39 #38 #24

**Comment by jtavva** [comment]
Duplicate of #24
