### ISSUE TITLE
Android Basics: Fragments Navigation component

### ISSUE THREAD

**Issue by Elmohound** [google-developer-training/android-basics-kotlin-words-app#71]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-fragments-navigation-component?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-3-pathway-2%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-fragments-navigation-component#3

**In which task and step of the codelab can this issue be found?**
Section 4. Create Fragment and layout Files
Step 3. (Edits to .xml files) 
Code for fragment_letter_list.xml

**Describe the problem**
Demonstrated text of fragment_letter_list.xml after editing tools:contexts shows:

   tools:context=".WordListFragment">

This value should be  ".LetterListFragment"

**Steps to reproduce?**
1. Go to... target of URL shown above.
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by jtavva** [comment]
Thank you so much for reporting this issue. This is fixed and will be published.
