### ISSUE TITLE
Android Basics: Collections

### ISSUE THREAD

**Issue by xtedx** [google-developer-training/android-basics-kotlin-words-app#75]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-collections?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-3-pathway-1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-collections#4

**In which task and step of the codelab can this issue be found?**
unit 3, task 2 codelab, section 5, step 2, just above step 3
<img width="372" alt="Screen Shot 2021-03-20 at 8 04 46 pm" src="https://user-images.githubusercontent.com/13181908/111864861-9498e280-89b7-11eb-880a-5449519550fc.png">

**Describe the problem**
this text is not supposed to be formated as code but as normal paragprah part of step 2
The  [`startsWith()`](https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.text/starts-with.html) function returns true if a string starts with the specified string. You can also tell it to ignore case, so "b" will match "b" or "B".

**Comment by calren** [comment]
This should now be fixed, thanks for filing!
