### ISSUE TITLE
Android Basics: Collections - Typo (text formatted as code)

### ISSUE THREAD

**Issue by charles-allen** [google-developer-training/android-basics-kotlin-words-app#77]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-collections#4

**In which task and step of the codelab can this issue be found?**
"5. Make word lists"

**Describe the problem**
In step 2, some explanation text is incorrectly formatted as code:

_Expected:_
The  [`startsWith()`](https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.text/starts-with.html) function returns true if a string starts with the specified string. You can also tell it to ignore case, so "b" will match "b" or "B".

_Actual:_
```
    The  [`startsWith()`](https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.text/starts-with.html) function returns true if a string starts with the specified string. You can also tell it to ignore case, so "b" will match "b" or "B".
```

**Comment by danielslabo** [comment]
Looks like a duplicate of #75

**Comment by charles-allen** [comment]
Yes it does! Closing...
