### ISSUE TITLE
Android Basics: Activities and intents

### ISSUE THREAD

**Issue by roblatta** [google-developer-training/android-basics-kotlin-words-app#8]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-activities-intents?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-3-pathway-1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-activities-intents#5

**In which task and step of the codelab can this issue be found?**
Task 6 Step 5

**Describe the problem**
It says "Remember when you performed the implicit intent in the WordAdapter, you passed in part of the URL to perform a Google search?" except there is no mention of WordAdapter or imlpementing an implicit intent in any of the previous tasks or steps of the codelab.

EDIT: It turns out you are asked to do this in the following task (task 7), however I'm fairly certain these tasks are the wrong way round as it is certainly confusing being asked to edit code you have not yet implemented and then the following task being asked to implement code which includes the part you were just asked to replace.

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by jtavva** [comment]
@roblatta 
Thank you so much for reporting this issue. This is fixed and will be published soon.
