### ISSUE TITLE
Android Basics: Collections

### ISSUE THREAD

**Issue by Pulkit-Kaushik** [google-developer-training/android-basics-kotlin-words-app#80]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-collections?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-3-pathway-1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-collections#3

**In which task and step of the codelab can this issue be found?**

**Describe the problem**
"The same pattern appears in the code that uses map and filter functions above"

This sentence is wrongly framed, as the map and filter function were explained on previous page and not "above" as stated in the sentence.

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by calren** [comment]
Thanks for pointing out this confusion, it should now be fixed!
