### ISSUE TITLE
Android Basics: Fragments Navigation component

### ISSUE THREAD

**Issue by caioiglesias** [google-developer-training/android-basics-kotlin-words-app#82]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-fragments-navigation-component?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-3-pathway-2%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-fragments-navigation-component#1

**In which task and step of the codelab can this issue be found?**
Download the starter code for this codelab

**Describe the problem**
The Starter Code URL points to the [solution branch](https://github.com/google-developer-training/android-basics-kotlin-words-app/tree/activities). I believe the intended one was:
https://github.com/google-developer-training/android-basics-kotlin-words-app/tree/starter

As a good example this [other codelab here](https://developer.android.com/codelabs/basic-android-kotlin-training-activities-intents?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-3-pathway-1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-activities-intents#1) even has the name of the branch listed along with the URL, which makes it even more clear:
![Screenshot 2021-04-08 at 23 17 50](https://user-images.githubusercontent.com/41685/114097702-b3a4d900-98c0-11eb-946d-bb5c88e978d7.png)

**Comment by danielslabo** [comment]
I'm not sure there is an issue with the repo being referenced, though adding to the webpage the explicit branch name of 'activities' for consistency sake can be considered the ask here. There are 3 branches for the words app source code:

1. main - my understanding is this is the solution
2. activities - I think this looks like the correct starting place for the Fragments and Navigation module, as it assumes a learner has either completed the words app from the Activities module and can use their own code or one can download from this branch as a starting point. This branch has not yet implemented fragments, which is the outcome of the Navigation/Fragments module, unlike 'main'
3. starter - used for beginning the words app when learning about Activities, the most basic source

I currently see it being referenced appropriately on the tutorial webpage:
Starter Code URL: https://github.com/google-developer-training/android-basics-kotlin-words-app/tree/activities

**Comment by caioiglesias** [comment]
You are right Daniel! I might have cloned the repo and ran the app from master 🙄 Sorry!
