### ISSUE TITLE
Android Basics: Fragments Navigation component

### ISSUE THREAD

**Issue by 2dnas** [google-developer-training/android-basics-kotlin-words-app#86]
**https://developer.android.com/codelabs/basic-android-kotlin-training-fragments-navigation-component?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-3-pathway-2%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-fragments-navigation-component#5**

**6. Convert DetailActivity to WordListFragment**

** In Section 7 where we implement onViewCreated() method, there should be onViewCreated() instead of onCreateView() 
at the end of the statement**

![mistake](https://user-images.githubusercontent.com/44274932/114468199-2c2ad300-9bfc-11eb-9d8c-3fe862c53791.PNG)

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by jtavva** [comment]
@2dnas 
Thank you so much for reporting this issue. This is fixed and will be published soon.
