### ISSUE TITLE
Android Basics: Fragments Navigation component

### ISSUE THREAD

**Issue by LeoGitGuy** [google-developer-training/android-basics-kotlin-words-app#87]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-fragments-navigation-component?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-3-pathway-2%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-fragments-navigation-component#3

**In which task and step of the codelab can this issue be found?**
Step 4.3

**Describe the problem**
The picture of "fragment_letter_list.xml" shows tools:context as ".WordListFragment". Instead it should be ".LetterListFragment" as described above in the instruction

**Comment by jtavva** [comment]
@LeoGitGuy 
Thank you so much for reporting this issue. This is fixed and will be published soon.
