### ISSUE TITLE
Android Basics: Fragments Navigation component

### ISSUE THREAD

**Issue by cory-austin** [google-developer-training/android-basics-kotlin-words-app#90]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-fragments-navigation-component?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-3-pathway-2%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-fragments-navigation-component#0

**In which task and step of the codelab can this issue be found?**
Task 2 step 1

**Describe the problem**
Fragment is misspelled as 'fragmen' in the third paragraph

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by jtavva** [comment]
@cory-austin 
Thank you so much for reporting this issue. This is fixed and will be published soon.
