### ISSUE TITLE
Android Basics: Fragments Navigation component

### ISSUE THREAD

**Issue by pokumars** [google-developer-training/android-basics-kotlin-words-app#94]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-fragments-navigation-component?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-3-pathway-2%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-fragments-navigation-component#0

**In which task and step of the codelab can this issue be found?**
Chapter 8 Using the Navigation Graph. Under the subheader "Use FragmentContainerView in MainActivity" step 3

**Describe the problem**
There is a typo of an XML attribute that has effects along the line. 
The codelab text says - add an attribute called `app:navHost` and set it equal to "true". However I am sure it meant `app:defaultNavHost`.
I think it is an error because 
1. when I try to build I get an error pointing to that
2. in the code snippet of what you should write, it says  `app:defaultNavHost`  and not `app:navHost`
3. The solution code also says  `app:defaultNavHost`  and not `app:navHost`

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._
![image](https://user-images.githubusercontent.com/33485810/115281005-36dfed80-a151-11eb-9405-f0a3206909bb.png)

**Comment by jtavva** [comment]
@pokumars 
Thank you so much for reporting this issue. This is fixed and will be published soon.
