### ISSUE TITLE
Android Basics: Fragments Navigation component

### ISSUE THREAD

**Issue by JoelRJ** [google-developer-training/android-basics-kotlin-words-app#96]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-fragments-navigation-component?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-3-pathway-2%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-fragments-navigation-component#0

**In which task and step of the codelab can this issue be found?**
Fragment is spelled _fragmen_ in the 3rd paragraph of **Before you begin** section (see below).

> You can even show multiple fragments at once on a single screen, such as a master-detail layout for tablet devices. In the example below, both the navigation UI on the left and the content on the right can each be contained in a separate **fragmen**. Both fragments exist simultaneously in the same activity.

**Comment by jtavva** [comment]
@JoelRJ 
Thank you so much for reporting this issue. This is fixed and will be published soon.
