### ISSUE TITLE
DetailedActivity is missing in the code.

### ISSUE THREAD

**Issue by ShoaibKakal** [google-developer-training/android-basics-kotlin-words-app#99]

**Comment by osuleymanova** [comment]
@ShoaibKakal 
Thank you for reaching out to us. We appreciate if you could provide any details where this issue is observed.

**Comment by johbess** [comment]
I have the same issue. When I clone the repo or download as Zip, the content is changed somehow. On my local machine I see LetterAdapter.kt, MainActivity.kt, WordListFragment.kt, LetterListFragment.kt and WordAdapter.kt. While if I look in the repo it looks correct.

Using MacOS Monterey 12.0.1
